export type PunishRule = {
	id: string;
	point: string;
	ruleName: string;
	banReason: string;
	warnText: string | null;
	recommendedDuration: string;
	note?: string;
};

export const PUNISH_RULES: PunishRule[] = [
	{
		id: 'r0',
		point: '0',
		ruleName: 'Незнание русского языка',
		banReason: "I'm sorry, but you need to know Russian to play on this server",
		warnText: null,
		recommendedDuration: 'Perm',
	},
	{
		id: 'r1.1',
		point: '1.1',
		ruleName: 'Никнейм',
		banReason: 'Смените никнейм и перезайдите на сервер',
		warnText: null,
		recommendedDuration: 'Perm по нику',
		note: 'Нечитаемые ники; ники с явно агрессивным политическим посылом.',
	},
	{
		id: 'r1.2a',
		point: '1.2',
		ruleName: 'Реклама',
		banReason: 'Реклама без разрешения администрации п.п. 1.2',
		warnText: null,
		recommendedDuration: 'Первый бан — 1 час, далее def',
	},
	{
		id: 'r1.2b',
		point: '1.2',
		ruleName: 'Реклама (ник)',
		banReason: 'Реклама в нике, смените никнейм п.п. 1.2',
		warnText: null,
		recommendedDuration: 'Perm по нику',
		note: 'Разрешена реклама своих каналов с контентом по игре.',
	},
	{
		id: 'r1.3a',
		point: '1.3',
		ruleName: 'Флуд (текст)',
		banReason: 'Флуд в текстовом чате п.п. 1.3',
		warnText: 'Прекратите флуд в чате.',
		recommendedDuration: 'Первый бан — 1 час, далее def',
	},
	{
		id: 'r1.3b',
		point: '1.3',
		ruleName: 'Флуд (голос)',
		banReason: 'Флуд в голосовом чате п.п. 1.3',
		warnText: null,
		recommendedDuration: 'Первый бан — 1 час, далее def',
	},
	{
		id: 'r1.4',
		point: '1.4',
		ruleName: 'Soundpad',
		banReason: 'Soundpad п.п. 1.4',
		warnText: null,
		recommendedDuration: 'Первый бан — 1 час, далее def',
	},
	{
		id: 'r1.5',
		point: '1.5',
		ruleName: 'Токсичность и провокации',
		banReason: 'Токсичное поведение и провокации п.п. 1.5',
		warnText: null,
		recommendedDuration: 'До 100ч/30ч: личн. оскорб. — 1ч, оскорб. родни/угрозы — 2д. От 100/30ч: 1д / 4д.',
		note: 'При повторном нарушении — ×2 срок. Оскорбление модератора в процессе работы — ×2 срок.',
	},
	{
		id: 'r1.6',
		point: '1.6',
		ruleName: 'Слив информации',
		banReason: 'Слив информации п.п. 1.6',
		warnText: null,
		recommendedDuration: 'Первый бан — 1 час, далее def',
	},
	{
		id: 'r1.7',
		point: '1.7',
		ruleName: 'Руин',
		banReason: 'Руин п.п. 1.7',
		warnText: null,
		recommendedDuration: 'На усмотрение администрации (агитация — def)',
		note: 'При массовом ТК убедиться, что не случайность. Перед баном проверять твинки и баны на других серверах.',
	},
	{
		id: 'r1.8a',
		point: '1.8',
		ruleName: 'Использование багов',
		banReason: 'Использование багов п.п. 1.8',
		warnText: null,
		recommendedDuration: 'На усмотрение администрации',
	},
	{
		id: 'r1.8b',
		point: '1.8',
		ruleName: 'Стороннее ПО (чит)',
		banReason: 'Использование стороннего ПО п.п. 1.8',
		warnText: null,
		recommendedDuration: 'Perm',
	},
	{
		id: 'r1.9',
		point: '1.9',
		ruleName: 'Мультиаккаунт',
		banReason: 'Мультиаккаунт для обхода бана п.п. 1.9',
		warnText: null,
		recommendedDuration: 'Perm на второй аккаунт | Удвоение срока на основном',
	},
	{
		id: 'r2.2.1a',
		point: '2.2.1',
		ruleName: 'Уничтожение техники у мейна',
		banReason: 'Уничтожение техники у мейна п.п. 2.2.1',
		warnText: 'Мейнкемп запрещён, отойдите от мейна.',
		recommendedDuration: 'Первый бан — 1 час, далее def',
	},
	{
		id: 'r2.2.1b',
		point: '2.2.1',
		ruleName: 'Установка мин у мейна',
		banReason: 'Установка мин на выезде с мейна п.п. 2.2.1',
		warnText: 'Мейнкемп запрещён, уберите мины.',
		recommendedDuration: 'Первый бан — 1 час, далее def',
	},
	{
		id: 'r2.2.1c',
		point: '2.2.1',
		ruleName: 'Блокирование мейна техникой',
		banReason: 'Блокирование мейна техникой п.п. 2.2.1',
		warnText: null,
		recommendedDuration: 'Первый бан — 1 час, далее def',
	},
	{
		id: 'r2.2.2',
		point: '2.2.2',
		ruleName: 'Засады у мейна',
		banReason: 'Создание засад у мейна п.п. 2.2.2',
		warnText: 'Не рекомендуем проявлять боевую активность в данном месте. Сместитесь ближе к зоне боевой задачи.',
		recommendedDuration: 'Первый бан — 1 час, далее def',
	},
	{
		id: 'r2.2.3',
		point: '2.2.3',
		ruleName: 'Злоупотребление границей мейнкемпа',
		banReason: 'Злоупотребление мейнкемпом п.п. 2.2.3',
		warnText: null,
		recommendedDuration: 'Первый бан — 1 час, далее def',
	},
	{
		id: 'r3.1',
		point: '3.1',
		ruleName: 'СЛ без микрофона',
		banReason: 'Сквад-лидер без микрофона п.п. 3.1',
		warnText: 'Командир обязан иметь микрофон и выходить на связь в CMD чате (клавиша G).',
		recommendedDuration: 'Первый бан — 1 час, далее def',
		note: 'Если в скваде нет человека с микрофоном — роспуск отряда.',
	},
	{
		id: 'r3.2',
		point: '3.2',
		ruleName: 'Передача сквадного без согласия',
		banReason: 'Передача сквадного без согласия п.п. 3.2',
		warnText: null,
		recommendedDuration: 'Первый бан — 1 час, далее def',
	},
	{
		id: 'r3.4',
		point: '3.4',
		ruleName: 'Соло-закрытый отряд',
		banReason: 'Закрытый соло-пех отряд п.п. 3.4',
		warnText: 'Откройте отряд или зайдите в открытый.',
		recommendedDuration: 'Первый бан — 1 час, далее def',
	},
	{
		id: 'r4.1',
		point: '4.1',
		ruleName: 'Невыполнение приказов CMD',
		banReason: 'Невыполнение приказов CMD п.п. 4.1',
		warnText: 'Игнорирование приказов CMD запрещено.',
		recommendedDuration: 'Первый бан — 1 час, далее def',
	},
	{
		id: 'r4.2',
		point: '4.2',
		ruleName: 'Запрещённый приказ CMD',
		banReason: 'Выдача приказа, нарушающего правила п.п. 4.2',
		warnText: 'Выдан приказ, противоречащий правилам.',
		recommendedDuration: 'Первый бан — 1 час, далее def',
	},
	{
		id: 'r5.1',
		point: '5.1',
		ruleName: 'Превышение кол-ва спецотрядов',
		banReason: 'Превышено количество спецотрядов п.п. 5.1',
		warnText: 'Превышено количество специализированных отрядов, расформируйте отряд.',
		recommendedDuration: 'Первый бан — 1 час / роспуск отряда, далее def',
	},
	{
		id: 'r5.2a',
		point: '5.2',
		ruleName: 'Превышение лимита в спецотряде',
		banReason: 'Превышение лимита людей в спецотряде п.п. 5.2',
		warnText: 'Превышение лимита людей в спецотряде (максимум 6 человек).',
		recommendedDuration: 'Первый бан — 1 час / роспуск отряда, далее def',
	},
	{
		id: 'r5.2b',
		point: '5.2',
		ruleName: 'Тандем в стройбате',
		banReason: '(Тандему) Тандем в стройбате п.п. 5.2',
		warnText: '(Тандему) В отряде стройбата тандему запрещено находиться вне актуала.',
		recommendedDuration: 'Первый бан — 1 час, далее def',
	},
	{
		id: 'r6.1',
		point: '6.1',
		ruleName: 'Переклейм техники',
		banReason: 'Переклейм техники без разрешения п.п. 6.1',
		warnText: 'Переклейм техники запрещён.',
		recommendedDuration: 'Первый бан — 1 час, далее def',
	},
	{
		id: 'r6.2',
		point: '6.2',
		ruleName: 'Нарушение приоритета на технику',
		banReason: 'Нарушение приоритета на технику п.п. 6.2',
		warnText: 'Верните технику отряду с приоритетом.',
		recommendedDuration: 'Первый бан — 1 час, далее def',
	},
	{
		id: 'r6.3',
		point: '6.3',
		ruleName: 'Нарушение правил !roll',
		banReason: 'Нарушение правил !roll п.п. 6.3',
		warnText: 'Спор за технику решается за 1 минуту до её появления.',
		recommendedDuration: 'Первый бан — 1 час, далее def',
	},
	{
		id: 'r6.4',
		point: '6.4',
		ruleName: 'Игнорирование приоритета на старте',
		banReason: 'Игнорирование приоритета на старте п.п. 6.4',
		warnText: 'Верните технику отряду с приоритетом.',
		recommendedDuration: 'Первый бан — 1 час, далее def',
	},
	{
		id: 'r6.5',
		point: '6.5',
		ruleName: 'Приоритет пех. отряда',
		banReason: 'Игнорирование приоритета пех. отряда п.п. 6.5',
		warnText: null,
		recommendedDuration: 'Первый бан — 1 час, далее def',
	},
	{
		id: 'r6.6',
		point: '6.6',
		ruleName: 'Соло-техника',
		banReason: 'Соло-использование техники п.п. 6.6',
		warnText: 'Использование тяжёлой техники в соло запрещено.',
		recommendedDuration: 'Первый бан — 1 час, далее def',
	},
	{
		id: 'r6.7',
		point: '6.7',
		ruleName: 'Управление вертолётом без опыта',
		banReason: 'Управление вертолётом без опыта п.п. 6.7',
		warnText: null,
		recommendedDuration: 'Первый бан — 1 час, далее def',
	},
];
