const common = {
  BOT_TOKEN: "5e64e6cf-c0fd-45f3-9d10-08228325c7da",
  RCON_HOST: "185.207.214.49",
  RCON_PASSWORD: "s8K#dL9QwPz2Xy!",
  BACKEND_INTERNAL_URL: "http://127.0.0.1:4000",
  INTERNAL_BOT_TOKEN: "b92482f1-b907-46d5-b480-35f8a0ea165f",
  LOG_TAIL_MODE: "remote-ssh",
  SSH_HOST: "185.207.214.49",
  SSH_PORT: 22,
  SSH_USERNAME: "root",
  SSH_PASSWORD: "9MLwO4y_9d",
};

module.exports = {
  apps: [
    {
      name: "1-invasion",
      script: "./dist/index.js",
      env: {
        ...common,
        SERVER_ID: 1,
        SERVER_NAME: 'A',
        PORT: 4001,
        RCON_PORT: 21114,
        SERVER_PATH: '/home/squadserver/squad_server_a',
        SH_PATH: '/home/squadserver/start_a.sh',
        ROTATION_PATH: '/home/squadserver/admins/rotation/a/',
        ROTATION_FILE: 'LayerVoting.cfg',
        SQUAD_LOG_PATH: "/home/squadserver/squad_server_a/SquadGame/Saved/Logs/SquadGame.log",
        SERVER_CFG_PATH: "/home/squadserver/squad_server_a/SquadGame/ServerConfig/Server.cfg",
        active: true,
      },
    },
    {
      name: "2-supermod-all",
      script: "./dist/index.js",
      env: {
        ...common,
        SERVER_ID: 2,
        SERVER_NAME: 'B',
        PORT: 4002,
        RCON_PORT: 21144,
        SERVER_PATH: '/home/squadserver/squad_server_b',
        SH_PATH: '/home/squadserver/start_b.sh',
        ROTATION_PATH: '/home/squadserver/admins/rotation/b/',
        ROTATION_FILE: 'LayerVoting.cfg',
        SQUAD_LOG_PATH: "/home/squadserver/squad_server_b/SquadGame/Saved/Logs/SquadGame.log",
        SERVER_CFG_PATH: "/home/squadserver/squad_server_b/SquadGame/ServerConfig/Server.cfg",
        active: true,
      },
    },
    {
      name: "3-aas",
      script: "./dist/index.js",
      env: {
        ...common,
        SERVER_ID: 3,
        SERVER_NAME: 'C',
        PORT: 4003,
        RCON_PORT: 21134,
        SERVER_PATH: '/home/squadserver/squad_server_c',
        SH_PATH: '/home/squadserver/start_c.sh',
        ROTATION_PATH: '/home/squadserver/admins/rotation/c/',
        ROTATION_FILE: 'LayerVoting.cfg',
        SQUAD_LOG_PATH: "/home/squadserver/squad_server_c/SquadGame/Saved/Logs/SquadGame.log",
        SERVER_CFG_PATH: "/home/squadserver/squad_server_c/SquadGame/ServerConfig/Server.cfg",
        active: true,
      },
    },
    {
      name: "4-warzone",
      script: "./dist/index.js",
      env: {
        ...common,
        SERVER_ID: 4,
        SERVER_NAME: 'D',
        PORT: 4004,
        RCON_PORT: 21154,
        SERVER_PATH: '/home/squadserver/squad_server_d',
        SH_PATH: '/home/squadserver/start_d.sh',
        ROTATION_PATH: '/home/squadserver/admins/rotation/d/',
        ROTATION_FILE: 'LayerVoting.cfg',
        SQUAD_LOG_PATH: "/home/squadserver/squad_server_d/SquadGame/Saved/Logs/SquadGame.log",  
        SERVER_CFG_PATH: "/home/squadserver/squad_server_d/SquadGame/ServerConfig/Server.cfg",
        active: true,
      },
    },
    // {
    //   name: "5-training",
    //   script: "./dist/index.js",
    //   env: {
    //     ...common,
    //     SERVER_ID: 5,
    //     SERVER_NAME: 'E',
    //     PORT: 4005,
    //     RCON_PORT: 21164,
    //     SERVER_PATH: '/home/squadserver/squad_server_e',
    //     SH_PATH: '/home/squadserver/start_e.sh',
    //     ROTATION_PATH: '/home/squadserver/admins/rotation/e/',
    //     ROTATION_FILE: 'LayerVoting.cfg',
    //     SQUAD_LOG_PATH: "/home/squadserver/squad_server_e/SquadGame/Saved/Logs/SquadGame.log",
    //   },
    // },
    // {
    //   name: "6-event",
    //   script: "./dist/index.js",
    //   env: {
    //     ...common,
    //     SERVER_ID: 6,
    //     SERVER_NAME: 'F',
    //     PORT: 4006,
    //     RCON_PORT: 21174,
    //     SERVER_PATH: '/home/squadserver/squad_server_f',
    //     SH_PATH: '/home/squadserver/start_f.sh',
    //     ROTATION_PATH: '/home/squadserver/admins/rotation/f/',
    //     ROTATION_FILE: 'LayerVoting.cfg',
    //     SQUAD_LOG_PATH: "/home/squadserver/squad_server_f/SquadGame/Saved/Logs/SquadGame.log",
    //   },
    // },
    // {
    //   name: "7-event",
    //   script: "./dist/index.js",
    //   env: {
    //     ...common,
    //     SERVER_ID: 7,
    //     SERVER_NAME: 'G',
    //     PORT: 4007,
    //     RCON_PORT: 21184,
    //     SERVER_PATH: '/home/squadserver/squad_server_g',
    //     SH_PATH: '/home/squadserver/start_g.sh',
    //     ROTATION_PATH: '/home/squadserver/admins/rotation/g/',
    //     ROTATION_FILE: 'LayerVoting.cfg',
    //     SQUAD_LOG_PATH: "/home/squadserver/squad_server_g/SquadGame/Saved/Logs/SquadGame.log",
    //   },
    // },
    // {
    //   name: "8-event",
    //   script: "./dist/index.js",
    //   env: {
    //     ...common,
    //     SERVER_ID: 8,
    //     SERVER_NAME: 'H',
    //     PORT: 4008,
    //     RCON_PORT: 21194,
    //     SERVER_PATH: '/home/squadserver/squad_server_h',
    //     SH_PATH: '/home/squadserver/start_h.sh',
    //     ROTATION_PATH: '/home/squadserver/admins/rotation/h/',
    //     ROTATION_FILE: 'LayerVoting.cfg',
    //     SQUAD_LOG_PATH: "/home/squadserver/squad_server_h/SquadGame/Saved/Logs/SquadGame.log",
    //   },
    // },
  ],
};
