type Weapon = Record<string, string>;

export const weapons: Weapon = {
	'2a6_Knockedout_Desert': 'Leopard 2A6 Knocked Out (Desert)',
	'ACV15_APC_Destroy': 'ACV-15 APC Destroyed',
	'ACV15_AmmoCook_Desert': 'ACV-15 Ammo Cookoff (Desert)',
	'ACV15_Burn': 'ACV-15 Burned',
	'ACV_M252_AP': 'ACV 25mm M242 Armor Piercing',
	'ACV_M252_AP_Desert': 'ACV 25mm M242 Armor Piercing',
	'ACV_M252_HE': 'ACV 25mm M242 High Explosive',
	'ASLAV_762': 'ASLAV 7.62mm Coaxial Machine Gun',
	'ASLAV_Burn': 'ASLAV Burned',
	'ASLAV_M252_AP': 'ASLAV 25mm M242 Armor Piercing',
	'ASLAV_M252_HE': 'ASLAV 25mm M242 High Explosive',
	'ASLAV_Obliterate': 'ASLAV Obliterated',
	'AUS_Utility_Truck_Destroyed': 'AUS Utility Truck Destroyed',
	'BFV_M252_AP_Woodland': 'Bradley 25mm M242 Armor Piercing (Woodland)',
	'BFV_M252_HE_Woodland': 'Bradley 25mm M242 High Explosive (Woodland)',
	'BMP1_Ammocook_MIL': 'BMP-1 Militia Ammo Cookoff',
	'BP_2A20_AP': '2A20 115mm Armor Piercing',
	'BP_2A20_Frag': '2A20 115mm Fragmentation',
	'BP_2A20_coax': '2A20 Coaxial Machine Gun',
	'BP_2A45_AP': '2A45 Sprut-B Armor Piercing',
	'BP_2A45_HEAT': '2A45 Sprut-B HEAT',
	'BP_2A45_coax': '2A45 Coaxial Machine Gun',
	'BP_2A46M_AP': '2A46M 125mm Armor Piercing',
	'BP_2A46M_coax': '2A46M Coaxial Machine Gun',
	'BP_2A46_AP': '2A46 125mm Armor Piercing',
	'BP_2A46_T72A_AP': 'T-72A 2A46 125mm Armor Piercing',
	'BP_2A46_T72A_coax': 'T-72A 2A46 Coaxial Machine Gun',
	'BP_2A46_T72S_coax': 'T-72S 2A46 Coaxial Machine Gun',
	'BP_2A46_coax': '2A46 Coaxial Machine Gun',
	'BP_30mm_VOG19_Proj': '30mm VOG-19 Grenade',
	'BP_35MM_Proj_QLZ87_HEDP': '35mm QLZ-87 HEDP Grenade',
	'BP_40MM_MK19_Proj': '40mm Mk19 Grenade',
	'BP_40MM_Proj2': '40mm High Explosive Grenade',
	'BP_40MM_VOG_Proj2': '40mm VOG Grenade',
	'BP_50Cal_M1128_Woodland': 'M1128 Stryker .50 cal HMG',
	'BP_50Cal_M1151': 'M1151 .50 cal HMG',
	'BP_50Cal_M1151_Black': 'M1151 Technical .50 cal HMG',
	'BP_50Cal_M1151_USMC_Woodland': 'M1151 USMC .50 cal HMG (Woodland)',
	'BP_50Cal_M1151_Woodland': 'M1151 HMMWV .50 cal HMG',
	'BP_6H9_Bayonet': '6H9 Bayonet',
	'BP_9K38_Igla': '9K38 Igla',
	'BP_AAVP7A1_M2_Woodland': 'AAVP7A1 M2 .50 cal HMG (Woodland)',
	'BP_ACV-15_MG3': 'ACV-15 MG3 7.62mm MG',
	'BP_ACV15_OpenTurret_M2_Weapon': 'ACV-15 Open Turret M2 .50 cal HMG',
	'BP_ACV15_OpenTurret_MG3_Weapon': 'ACV-15 Open Turret MG3 7.62mm MG',
	'BP_ACV_762_Desert': 'ACV 7.62mm Coaxial Machine Gun',
	'BP_ADF_Binoculars': 'Field Binoculars',
	'BP_AGS30_40MM_VOG_Proj': 'AGS-30 40mm VOG Grenade',
	'BP_AK101_PushCO_EXPS': 'AK-101 PushCo + EXPS',
	'BP_AK101_PushCO_Foregrip': 'AK-101 PushCo + Foregrip',
	'BP_AK101_PushCO_M150_Foregrip': 'AK-101 PushCo + TA31 + Foregrip',
	'BP_AK101_PushCO_T800_Foregrip': 'AK-101 PushCo + T800 + Foregrip',
	'BP_AK103GP25_TA01_Rifle_SuperMod': 'AK133-GP25 TA01',
	'BP_AK103GP25_TA01_UGL_HE_OGL': 'GP-25 Fragmentation',
	'BP_AK103GP25_TA01_UGL_Smoke_Blue_OGL': 'GP-25 Smoke Marker Blue',
	'BP_AK103GP25_TA01_UGL_Smoke_OGL': 'GP-25 Smoke Marker White',
	'BP_AK103GP25_TA01_UGL_Smoke_Red_OGL': 'GP-25 Smoke Marker Red',
	'BP_AK103_MRS_Foregrip': 'AK-103 + MRS',
	'BP_AK12': 'AK-12',
	'BP_AK12GP25_Rifle': 'AK-12 GP-25',
	'BP_AK12GP25_Rifle_1P78Picatinny': 'AK-12 GP-25 + 1P78',
	'BP_AK12GP25_Rifle_Reddot': 'AK-12 GP-25 + 1P87',
	'BP_AK12GP25_UGL_1P78Picatinny_HE': 'GP-25 High Explosive',
	'BP_AK12GP25_UGL_1P78Picatinny_HE_2rnds': 'GP-25 High Explosive',
	'BP_AK12GP25_UGL_1P78Picatinny_Smoke': 'GP-25 Smoke (White)',
	'BP_AK12GP25_UGL_HE_2rnds': 'GP-25 High Explosive',
	'BP_AK12GP25_UGL_Reddot_HE': 'GP-25 High Explosive',
	'BP_AK12GP25_UGL_Reddot_HE_2rnds': 'GP-25 High Explosive',
	'BP_AK12GP25_UGL_Reddot_Smoke': 'GP-25 Smoke (White)',
	'BP_AK12GP25_UGL_Smoke': 'GP-25 Smoke Marker White',
	'BP_AK12_1P78Picatinny': 'AK-12 + 1P78',
	'BP_AK12_1mags': 'AK-12',
	'BP_AK12_4mags': 'AK-12',
	'BP_AK12_Foregrip': 'AK-12 + Foregrip',
	'BP_AK12_Foregrip_1P78Picatinny': 'AK-12 + 1P78 + Foregrip',
	'BP_AK12_Foregrip_Reddot': 'AK-12 + 1P87 + Foregrip',
	'BP_AK12_Reddot': 'AK-12 + 1P87',
	'BP_AK74': 'AK-74',
	'BP_AK74Bayonet': 'AK-74 Bayonet',
	'BP_AK74GP25_1P63_UGL_HE_10Rnds': 'GP-25 Fragmentation',
	'BP_AK74GP25_1P63_UGL_HE_2Rnds': 'GP-25 Fragmentation',
	'BP_AK74GP25_1P63_UGL_Smoke': 'GP-25 Smoke (White)',
	'BP_AK74GP25_1P63_UGL_Smoke_Blue': 'GP-25 Smoke (Blue)',
	'BP_AK74GP25_1P63_UGL_Smoke_Red': 'GP-25 Smoke (Red)',
	'BP_AK74GP25_EXPS_UGL_HE_10Rnds': 'GP-25 Fragmentation',
	'BP_AK74GP25_EXPS_UGL_Smoke': 'GP-25 Smoke (White)',
	'BP_AK74GP25_EXPS_UGL_Smoke_Blue': 'GP-25 Smoke (Blue)',
	'BP_AK74GP25_EXPS_UGL_Smoke_Red': 'GP-25 Smoke (Red)',
	'BP_AK74GP25_Pro_Rifle': 'AK-74 GP-25',
	'BP_AK74GP25_Rifle_1P63': 'AK-74 GP-25 + 1P63',
	'BP_AK74GP25_Rifle_EXPS_Pro': 'AK-74 GP-25 + EXPS',
	'BP_AK74GP25_Rifle_HHS1': 'AK-74 GP-25  HHS1',
	'BP_AK74GP25_UGL_Elcan_Smoke': 'GP-25 Smoke (White)',
	'BP_AK74GP25_UGL_Elcan_Smoke_Blue': 'GP-25 Smoke Marker Blue',
	'BP_AK74GP25_UGL_Elcan_Smoke_Red': 'GP-25 Smoke Marker Red',
	'BP_AK74GP25_UGL_HE': 'GP-25 Fragmentation',
	'BP_AK74GP25_UGL_HE_Elcan': 'GP-25 Fragmentation',
	'BP_AK74GP25_UGL_HE_HHS1': 'GP-25 Fragmentation',
	'BP_AK74GP25_UGL_HHS1_Smoke': 'GP-25 Smoke (White)',
	'BP_AK74GP25_UGL_HHS1_Smoke_Blue': 'GP-25 Smoke Marker Blue',
	'BP_AK74GP25_UGL_HHS1_Smoke_Red': 'GP-25 Smoke Marker Red',
	'BP_AK74GP25_UGL_Smoke': 'GP-25 Smoke (White)',
	'BP_AK74GP25_UGL_Smoke_Blue': 'GP-25 Smoke (Blue)',
	'BP_AK74GP25_UGL_Smoke_Red': 'GP-25 Smoke (Red)',
	'BP_AK74M': 'AK-74M',
	'BP_AK74M3GP25_1P78_NoRub_UGL_HE': 'GP-25 Fragmentation',
	'BP_AK74M3GP25_1P78_NoRub_UGL_Parent': 'GP-25 High Explosive',
	'BP_AK74M3GP25_1P78_NoRub_UGL_Smoke_Blue': 'GP-25 Smoke Marker Blue',
	'BP_AK74M3GP25_1P78_NoRub_UGL_Smoke_Red': 'GP-25 Smoke Marker Red',
	'BP_AK74M3GP25_Rifle_1P78_NoRub': 'AK-74M3 VDV + GP-25 + 1P78 + No Rubber',
	'BP_AK74M3_1P90_Grip_VDV': 'AK-74M3 + 1P87 + 1P90 + Foregrip',
	'BP_AK74MGP25_1P63_UGL_HE': 'GP-25 High Explosive',
	'BP_AK74MGP25_1P63_UGL_Smoke': 'GP-25 Smoke (White)',
	'BP_AK74MGP25_1P63_UGL_Smoke_Blue': 'GP-25 Smoke (Blue)',
	'BP_AK74MGP25_1P63_UGL_Smoke_Red': 'GP-25 Smoke (Red)',
	'BP_AK74MGP25_1P78_UGL_HE': 'GP-25 High Explosive',
	'BP_AK74MGP25_1P78_UGL_Smoke': 'GP-25 Smoke (White)',
	'BP_AK74MGP25_1P78_UGL_Smoke_Blue': 'GP-25 Smoke (Blue)',
	'BP_AK74MGP25_1P78_UGL_Smoke_Red': 'GP-25 Smoke (Red)',
	'BP_AK74MGP25_RSF_1P78_UGL_HE_MEE': 'GP-25 Fragmentation',
	'BP_AK74MGP25_RSF_1P78_UGL_Smoke_Blue_MEE': 'GP-25 Smoke Marker Blue',
	'BP_AK74MGP25_RSF_1P78_UGL_Smoke_MEE': 'GP-25 Smoke Marker White',
	'BP_AK74MGP25_RSF_1P78_UGL_Smoke_Red_MEE': 'GP-25 Smoke Marker Red',
	'BP_AK74MGP25_Rifle_1P63': 'AK-74M GP-25 + 1P63',
	'BP_AK74MGP25_Rifle_1P78': 'AK-74M GP-25 + 1P78',
	'BP_AK74M_1P63': 'AK-74M + 1P63',
	'BP_AK74M_1P78': 'AK-74M + 1P78',
	'BP_AK74M_1mag': 'AK-74M',
	'BP_AK74_1mag': 'AK-74',
	'BP_AK74_45rnd_Foregrip': 'AK-74 + Foregrip + Extended Mag',
	'BP_AK74_EXPS_Pro': 'AK-74 + EXPS',
	'BP_AK74_OKP7_Pro': 'AK-74 + OKP-7',
	'BP_AK74_Pro': 'AK-74',
	'BP_AK74_Pro_1mag': 'AK-74',
	'BP_AK74_Yoloson_Pro': 'AK-74 + Yoloson',
	'BP_AKM': 'AKM',
	'BP_AKMBayonet': 'AKM Bayonet',
	'BP_AKMGP25_Rifle': 'AKM GP-25',
	'BP_AKMGP25_UGL_HE': 'GP-25 Fragmentation',
	'BP_AKMGP25_UGL_HE_MEE': 'GP-25 Fragmentation',
	'BP_AKMGP25_UGL_Smoke': 'GP-25 Smoke (White)',
	'BP_AKMGP25_UGL_Smoke_Blue': 'GP-25 Smoke (Blue)',
	'BP_AKMGP25_UGL_Smoke_Blue_MEE': 'GP-25 Smoke Marker Blue',
	'BP_AKMGP25_UGL_Smoke_MEE': 'GP-25 Smoke Marker White',
	'BP_AKMGP25_UGL_Smoke_Red': 'GP-25 Smoke (Red)',
	'BP_AKMGP25_UGL_Smoke_Red_MEE': 'GP-25 Smoke Marker Red',
	'BP_AKMS': 'AKMS',
	'BP_AKM_1mag': 'AKM',
	'BP_AKM_Drummag': 'AKM + Drum Mag',
	'BP_AKM_IMF': 'AKM',
	'BP_AKS74': 'AKS-74',
	'BP_AKS74U': 'AKS-74U',
	'BP_AKS74U_45Rnd': 'AKS-74U + Extended Mag',
	'BP_AKS74U_4mags': 'AKS-74U',
	'BP_AKS74U_Pro_45Rnd': 'AKS-74U + Extended Mag',
	'BP_AKS74U_RUS_4mags': 'AKS-74U',
	'BP_AKS74U_Yoloson': 'AKS-74U + Yoloson',
	'BP_AKS74_1P29': 'AKS-74 + 1P29',
	'BP_AKS74_1P63': 'AKS-74 + 1P63',
	'BP_AKS74_1P78': 'AKS-74 + 1P78',
	'BP_AKS74_PSO-1_Pro': 'AKS-74 + PSO-1',
	'BP_AKS74_Pro_4Mags': 'AKS-74',
	'BP_AKS74_Rus': 'AKS-74',
	'BP_AMD65': 'AMD-65',
	'BP_APKWS_Proj2': 'APKWS Rocket',
	'BP_ASLAV': 'ASLAV',
	'BP_ASVAL': 'AS-VAL',
	'BP_ASVAL_OKP-7': 'AS-VAL + OKP-7',
	'BP_ASVAL_Optic': 'AS-VAL + PSO-1-1',
	'BP_AT3_Proj2': 'AT-3 Sagger Missile',
	'BP_AT4_Rocket_Proj2': 'AT4 Rocket',
	'BP_AUG': 'AUG',
	'BP_Angenieux': 'Angenieux',
	'BP_Arbalet_Kord': 'Arbalet Kord 12.7mm HMG',
	'BP_BM21Grad_Weapon_IMF': 'BM-21 Grad Rocket Launcher (IMF)',
	'BP_BM21_Rocket_Proj2': 'BM-21 Grad Rocket',
	'BP_BMD1M_Bow_PKT': 'BMD-1M Bow PKT 7.62mm Machine Gun',
	'BP_BMD4M': 'BMD-4M',
	'BP_BMD4M_2A70_coax': 'BMD-4M 2A70 Coaxial Gun',
	'BP_BMD4M_2A72_AP': 'BMD-4M 2A72 30mm Armor Piercing',
	'BP_BMP1TS_ZTM1_AP': 'BMP-1TS ZTM-1 30mm Armor Piercing',
	'BP_BMP1_PKT': 'BMP-1 PKT 7.62mm Coaxial Machine Gun',
	'BP_BMP2M_2A42_AP': 'BMP-2M 2A42 30mm Armor Piercing',
	'BP_BMP2M_Ammocook': 'BMP-2M Ammo Cookoff',
	'BP_BMP2_2A42_AP': 'BMP-2 2A42 30mm Armor Piercing',
	'BP_BMP2_2A42_HE': 'BMP-2 2A42 30mm High Explosive',
	'BP_BMP2_AFU_2A42_AP': 'BMP-2 AFU 2A42 30mm Armor Piercing',
	'BP_BMP2_GFI': 'BMP-2 GFI',
	'BP_BMP2_GFI_2A42_AP': 'BMP-2 GFI 2A42 30mm Armor Piercing',
	'BP_BMP2_GFI_PKT': 'BMP-2 GFI PKT 7.62mm Coaxial Machine Gun',
	'BP_BMP2_IMF': 'BMP-2 IMF',
	'BP_BMP2_PKT': 'BMP-2 PKT 7.62mm Coaxial Machine Gun',
	'BP_BMP3M_2A72_AP': 'BMP-3M 2A72 30mm Armor Piercing',
	'BP_BMP3M_Ammocook': 'BMP-3M Ammo Cookoff',
	'BP_BRDM-2_RUS': 'BRDM-2 RUS',
	'BP_BRDM2_AFU_KPVT': 'BRDM-2 AFU KPVT 14.5mm HMG',
	'BP_BRDM2_AFU_PKT': 'BRDM-2 AFU PKT 7.62mm Machine Gun',
	'BP_BRDM2_GFI_KPVT': 'BRDM-2 GFI KPVT 14.5mm HMG',
	'BP_BRDM2_GFI_PKT': 'BRDM-2 GFI PKT 7.62mm Machine Gun',
	'BP_BRDM2_INS_KPVT': 'BRDM-2 INS KPVT 14.5mm HMG',
	'BP_BRDM2_RUS_KPVT': 'BRDM-2 RUS KPVT 14.5mm HMG',
	'BP_BRDM2_RUS_PKT': 'BRDM-2 RUS PKT 7.62mm Machine Gun',
	'BP_BTR-DG_Logistics': 'BTR-DG Logistics',
	'BP_BTR4_ZTM1_AP': 'BTR-4 ZTM-1 30mm Armor Piercing',
	'BP_BTR80_GFI_KPVT': 'BTR-80 GFI KPVT 14.5mm HMG',
	'BP_BTR80_GFI_PKT': 'BTR-80 GFI PKT 7.62mm Machine Gun',
	'BP_BTR80_RUS_KPVT': 'BTR-80 RUS KPVT 14.5mm HMG',
	'BP_BTR80_RUS_PKT': 'BTR-80 RUS PKT 7.62mm Machine Gun',
	'BP_BTR82A_PKT': 'BTR-82A PKT 7.62mm Coaxial Machine Gun',
	'BP_BTR82A_RUS_2A72_AP': 'BTR-82A 2A72 30mm Armor Piercing',
	'BP_BTR82A_RUS_2A72_AP_Desert': 'BTR-82A RUS 2A72 30mm Armor Piercing (Desert)',
	'BP_BTRMDM_Bow_PKT': 'BTR-MDM bow gun PKT 7.62mm MG',
	'BP_BW_Binoculars': 'Fero D16 Binoculars',
	'BP_BW_P8': 'HK P8',
	'BP_BW_TerrapinX': 'Terrapin X',
	'BP_Bayonet2000': 'Bayonet2000',
	'BP_Brit_Util_Truck': 'British Utility Truck',
	'BP_BrowningHP': 'Hi-Power',
	'BP_BrowningHP_ADF': 'Self-Loading Pistol Mk3',
	'BP_Browning_P35': 'Hi-Power',
	'BP_Browning_P35_5Mags': 'Hi-Power',
	'BP_C13Frag': 'C13 Fragmentation Grenade',
	'BP_C14': 'C14 MRSWS',
	'BP_C16_C6': 'C16 C6 7.62mm Machine Gun',
	'BP_C16_C6_Desert': 'C16 C6 7.62mm Machine Gun (Desert)',
	'BP_C6': 'C6',
	'BP_C6A1': 'C6A1 FLEX',
	'BP_C7A2_1mag': 'C7A2',
	'BP_C7A2_C79A2': 'C7A2 + C79A2',
	'BP_C7A2_C79A2_Foregrip': 'C7A2 + C79A2 + Foregrip',
	'BP_C7A2_C79A2_M203A1': 'C7A2 M203A1 + C79A2',
	'BP_C7A2_ET552_Foregrip': 'C7A2 + ET552 + Foregrip',
	'BP_C7A2_Ironsights': 'C7A2',
	'BP_C7A2_Ironsights_Foregrip': 'C7A2 + Foregrip',
	'BP_C7A2_M203A1_C79A2_UGL_HE': 'M203A1 High Explosive',
	'BP_C7A2_M203A1_C79A2_UGL_Smoke': 'M203A1 Smoke (White)',
	'BP_C7A2_M203A1_C79A2_UGL_Smoke_Blue': 'M203A1 Smoke (Blue)',
	'BP_C7A2_M203A1_C79A2_UGL_Smoke_Red': 'M203A1 Smoke (Red)',
	'BP_C8A3_C79A2': 'C8A3 + C79A2',
	'BP_C8A3_C79A2_Foregrip': 'C8A3 + C79A2 + Foregrip',
	'BP_C8A3_ET552_Foregrip': 'C8A3 + ET552 + Foregrip',
	'BP_C8A3_ET552_M203': 'C8A3 M203A1 + ET552',
	'BP_C8A3_Ironsights_4mags': 'C8A3',
	'BP_C8A3_Ironsights_Foregrip': 'C8A3 + Foregrip',
	'BP_C8A3_M203_ET_UGL_HE': 'M203A1 High Explosive',
	'BP_C8A3_M203_ET_UGL_Smoke': 'M203A1 Smoke (White)',
	'BP_C8A3_M203_ET_UGL_Smoke_Blue': 'M203A1 Smoke (Blue)',
	'BP_C8A3_M203_ET_UGL_Smoke_Red': 'M203A1 Smoke (Red)',
	'BP_C90CR': 'C90-CR',
	'BP_C90CR_2mags': 'C90-CR',
	'BP_C90_Rocket_Proj': 'C90 Rocket',
	'BP_C9A2': 'C9A2',
	'BP_C9A2_C79A2': 'C9A2 + C79A2',
	'BP_C9A2_Foregrip': 'C9A2 CQB + Foregrip',
	'BP_CROWS_M2': 'CROWS M2 .50 cal HMG',
	'BP_CROWS_M2_Woodland': 'CROWS M2 .50 cal HMG (Woodland)',
	'BP_CROWS_M2_Woodland_Green': 'CROWS M2 .50 cal HMG (Woodland Green)',
	'BP_CarlGustavM2_2x_FFV551_No78Mk1': 'M2 Carl Gustav (FFV551 HEAT)',
	'BP_CarlGustavM2_FFV441D_No78Mk1': 'M2 Carl Gustav (FFV441D HE)',
	'BP_CarlGustavM2_FFV441D_No78Mk1_2': 'M2 Carl Gustav (FFV441D HE)',
	'BP_CarlGustavM2_FFV551_No78Mk1': 'M2 Carl Gustav (FFV551 HEAT)',
	'BP_CarlGustavM2_FFV751_No78Mk1': 'M2 Carl Gustav (FFV751 Tandem)',
	'BP_CarlGustavM2_FFV751_No78Mk1_2mags': 'M2 Carl Gustav (FFV751 Tandem)',
	'BP_Coyote_762_Woodland': 'Coyote 7.62mm Coaxial Machine Gun',
	'BP_Cupola_Dshk_MIL': 'Militia DShK Cupola 12.7mm HMG',
	'BP_Cupola_QJZ89_Naval': 'Naval QJZ-89 Cupola Weapon',
	'BP_DZJ-08': 'DZJ-08',
	'BP_Deployable_IED': 'IED',
	'BP_Deployable_M112_C4Explosive': 'M112 C4 Explosive',
	'BP_Deployable_M112_C4Explosive_Timed': 'M112 C4 Timed Explosive',
	'BP_Deployable_M15Mine': 'M15 Anti-Tank Mine',
	'BP_Deployable_SZ1_Explosives_Timed': 'SZ-1 Timed Explosive',
	'BP_Deployable_SensitiveExplosives_Bangerite': 'Bangerite Sensitive Explosive',
	'BP_Deployable_TM62Mine': 'TM-62 Anti-Tank Mine',
	'BP_Deployable_TNT_1lb_Explosive_Timed': '1 lb TNT Timed Explosive',
	'BP_Deployable_TNT_600g_Explosive_Timed': '600 g TNT Timed Explosive',
	'BP_Deployable_Type72Mine': 'Type 72 Anti-Tank Mine',
	'BP_Desert_Eagle': 'Desert Eagle',
	'BP_EF88C_ET552_Foregrip': 'EF88C + ET552',
	'BP_EF88C_ET552_Foregrip_4Mags': 'EF88C + ET552',
	'BP_EF88C_Specter_Foregrip': 'EF88C + Specter',
	'BP_EF88_ET552_Foregrip': 'EF88 + ET552',
	'BP_EF88_ET552_Grippod': 'EF88 + ET552 + Grippod',
	'BP_EF88_Ironsight_Foregrip': 'EF88',
	'BP_EF88_Ironsight_Foregrip_1mag': 'EF88',
	'BP_EF88_Ironsight_Grippod': 'EF88 + Grippod',
	'BP_EF88_SL40_UGL_HE': 'SL40 High Explosive',
	'BP_EF88_SL40_UGL_HE_SuperMod': 'SL40 High Explosive',
	'BP_EF88_SL40_UGL_Smoke': 'SL40 Smoke (White)',
	'BP_EF88_SL40_UGL_Smoke_Blue': 'SL40 Smoke (Blue)',
	'BP_EF88_SL40_UGL_Smoke_Blue_SuperMod': 'SL40 Smoke (Blue)',
	'BP_EF88_SL40_UGL_Smoke_Red': 'SL40 Smoke (Red)',
	'BP_EF88_SL40_UGL_Smoke_Red_SuperMod': 'SL40 Smoke (Red)',
	'BP_EF88_SL40_UGL_Smoke_SuperMod': 'SL40 Smoke (White)',
	'BP_EF88_Specter_Foregrip': 'EF88 + Specter',
	'BP_EF88_Specter_Grippod': 'EF88 + Specter + Grippod',
	'BP_EF88_Specter_SL40': 'EF88 SL40 + Specter',
	'BP_EF88_Specter_SL40_SuperMod': 'EF88 + ELCAN Specter + SL40 + Frontgrip',
	'BP_EmplacedDshk_Shield': 'Emplaced DShK Shielded 12.7mm HMG',
	'BP_EmplacedKord_SPP': 'Emplaced Kord SPP 12.7mm HMG',
	'BP_EmplacedM2HB_Shield_Weapon': 'Emplaced M2HB Shielded .50 cal HMG',
	'BP_EmplacedM2_Weapon_ACOG': 'Emplaced M2 .50 cal HMG + ACOG',
	'BP_EmplacedM2_Weapon_Ironsight': 'Emplaced M2 .50 cal HMG + Ironsight',
	'BP_EmplacedQJZ-89_Scope': 'Emplaced QJZ-89 + Scope',
	'BP_EnforcerRWS_L37A2': 'Enforcer RWS L37A2 7.62mm MG',
	'BP_EnforcerRWS_L37A2_Woodland': 'Enforcer RWS L37A2 7.62mm MG',
	'BP_EnforcerRWS_M2': 'Enforcer RWS M2 .50 cal HMG',
	'BP_EnforcerRWS_M2_Woodland': 'Enforcer RWS M2 .50 cal HMG',
	'BP_F1Frag': 'F1 Fragmentation Grenade',
	'BP_F1Frag_au': 'F1 Fragmentation Grenade (ADF)',
	'BP_F89_ET552': 'F89 + ET552',
	'BP_F89_Specter': 'F89 + Specter',
	'BP_FAMAS_Bayonet': 'FAMAS Bayonet',
	'BP_FAMAS_BayonetRifle': 'FAMAS Bayonet',
	'BP_FFV441D_Rocket_Proj': 'Carl Gustav FFV441D HE Rocket',
	'BP_FFV551_Rocket_Proj2': 'Carl Gustav FFV551 HEAT Rocket',
	'BP_FFV751_Tandem_Heat_Proj2': 'Carl Gustav FFV751 Tandem HEAT Rocket',
	'BP_FIM-92': 'FIM-92 Stinger',
	'BP_FNFAL': 'FN FAL',
	'BP_FNFAL_GL_Frag': 'Rifle Grenade (Fragmentation)',
	'BP_FNFAL_GL_HEAT': 'Rifle Grenade (HEAT)',
	'BP_FNFAL_GL_HEAT_Rifle': 'FN FAL',
	'BP_FNFAL_GL_Rifle': 'FN FAL',
	'BP_FORT224_LongBarrel_M5_G33_': 'FORT224 .330 M5 + G33',
	'BP_FamasF1_UGL_AC_58': 'AC 58',
	'BP_Famas_INF_AIMPOINT_UGL_AC_58': 'AC 58',
	'BP_Famas_INF_AIMPoint_7mag_PIRAT': 'FAMAS F1 + Aimpoint',
	'BP_Famas_INF_SCROMEJ4_UGL_AC_58': 'AC 58',
	'BP_Famas_INF_SCROMEJ4_UGL_APAV_F2': 'APAV F2',
	'BP_Famas_INF_SCROMEJ4_UGL_FUM_47_Smoke': 'FUM 47',
	'BP_Famas_INF_SCROMEJ4_UGL_FUM_47_Smoke_Blue': 'FUM 47',
	'BP_Famas_INF_SCROMEJ4_UGL_FUM_47_Smoke_Red': 'FUM 47',
	'BP_Famas_INF_SCROME_J4_PIRAT': 'FAMAS F1 SCROME J4',
	'BP_Famas_Valorise_552_5mag': 'FAMAS Valorisé + EOTECH 552',
	'BP_Famas_Valorise_5mag': 'FAMAS Valorisé',
	'BP_G17': 'G17',
	'BP_G17_5Mags': 'G17',
	'BP_G17_ExtendedMag_33rd': 'G17 + Extended Mag',
	'BP_G17_ExtendedMag_33rd_4Mags': 'G17 + Extended Mag',
	'BP_G18_ExtendedMag_33rd': 'G18 + Extended Mag',
	'BP_G22A2': 'G22A2',
	'BP_G3A3': 'G3A3',
	'BP_G3A3HK79_Optic_Rifle': 'G3A3 HK79 + ZF1',
	'BP_G3A3HK79_Optic_UGL_HE': 'HK79 High Explosive',
	'BP_G3A3HK79_Optic_UGL_Smoke': 'HK79 Smoke (White)',
	'BP_G3A3HK79_Optic_UGL_Smoke_Blue': 'HK79 Smoke (Blue)',
	'BP_G3A3HK79_Optic_UGL_Smoke_Red': 'HK79 Smoke (Red)',
	'BP_G3A3_1mag': 'G3A3',
	'BP_G3A3_DMR': 'G3A3 DMR',
	'BP_G3A4_Foregrip': 'G3A4 + Foregrip',
	'BP_G3A4_Optic_Foregrip': 'G3A4 + ZF1 + Foregrip',
	'BP_G3A4_ZF_Foregrip_Tracer': 'G3A4 + ZF1 + Foregrip + Tracer',
	'BP_G3A4_ZPoint_Foregrip': 'G3A4 + Z-Point + Foregrip',
	'BP_G3A7_Foregrip': 'G3A7 + Foregrip',
	'BP_G3A7_ZPoint_Foregrip': 'G3A7 + Z-Point + Foregrip',
	'BP_G3Bayonet': 'G3 Bayonet',
	'BP_G3KA4_ZPoint': 'G3KA4 + Z-Point',
	'BP_G3KA4_ZPoint_Foregrip': 'G3KA4 + Z-Point + Foregrip',
	'BP_G3SG1_Optic': 'G3SG/1',
	'BP_GAU21_DoorGun': 'GAU-21 Door Gun',
	'BP_Generic_HKG36_KA3_EoTech_Foregrip_Suppressed': 'G36 KA3 EoTech Foregrip Suppressed',
	'BP_HAR66': 'HAR-66',
	'BP_HAR66_2mags': 'HAR-66',
	'BP_HJ-8ATGM_Proj': 'HJ-8 ATGM Missile',
	'BP_HK269_ELCAN_UGL_HE': 'HK269 HE',
	'BP_HK269_ELCAN_UGL_Smoke': 'HK269 Smoke',
	'BP_HK269_ELCAN_UGL_Smoke_Blue': 'HK269 Blue Smoke',
	'BP_HK269_ELCAN_UGL_Smoke_Red': 'HK269 Red Smoke',
	'BP_HK269_J4_UGL_HE': 'HK269 HE',
	'BP_HK269_J4_UGL_Smoke': 'HK269 Smoke',
	'BP_HK269_J4_UGL_Smoke_Blue': 'HK269 Blue Smoke',
	'BP_HK269_J4_UGL_Smoke_Red': 'HK269 Red Smoke',
	'BP_HK416F-C_4mag': 'HK416F-C',
	'BP_HK416F-C_CompM5_4mag': 'HK416F-C + CompM5',
	'BP_HK416F-S_ELCAN_HK269': 'HK416F-S + ELCAN Specter',
	'BP_HK416F-S_Eotech_4mag': 'HK416F-S + EOTECH 552',
	'BP_HK416F-S_SJ4_Foregrip': 'HK416F-S + SJ4 + Foregrip',
	'BP_HK416F-S_SJ4_HK269': 'HK416F-S + SJ4 + HK269',
	'BP_HK416_Bayonet': 'SG 2000 WC-F Bayonet',
	'BP_HK416_SDO': 'HK416 + SDO',
	'BP_HK417_Optic': 'HK417',
	'BP_HKG28_Optic': 'G28',
	'BP_HKG36_A3_ZF_RD_Child': 'G36 A3 ZF RD',
	'BP_HKG36_AG36_ZF_RD_Child': 'G36 AG36 ZF RD',
	'BP_HKG36_AG36_ZF_RD_Smoke': 'AG36 Smoke Marker White',
	'BP_HKG36_AG36_ZF_RD_Smoke_red_Child': 'AG36 Smoke Marker Red',
	'BP_HKG36_AG36_ZF_RD_Smoke_yellow_Child': 'AG36 Smoke Marker Yellow',
	'BP_HKG36_AG36_ZF_RD_UGL_Parent': 'AG36 High Explosive',
	'BP_HKG36_KA3_Foregrip_ZF_RD_4Mags': 'G36 KA3 ZF RD Foregrip',
	'BP_HKG36_KA3_Foregrip_ZF_RD_4Mags_Suppressed': 'G36 KA3 ZF RD Foregrip',
	'BP_HKG36_KA3_Foregrip_ZF_RD_Child': 'G36 KA3 ZF RD Foregrip',
	'BP_HKG36_KA3_Iron_Child': 'G36 KA3 iron Foregrip ',
	'BP_HKMP7_RD': 'MP7 RD',
	'BP_HKMP7_RD_4Mags': 'MP7 RD',
	'BP_Heavy_Mortarround4': '120mm Heavy Mortar Round',
	'BP_Hensoldt': 'Hensoldt',
	'BP_ILAWAT4': 'L2A1 ILAW',
	'BP_KBA3_AP': 'KBA-3 125mm Armor Piercing',
	'BP_KBA3_coax': 'KBA-3 Coaxial Machine Gun',
	'BP_KLF': 'KLF',
	'BP_KLS': 'KLS',
	'BP_KM2000': 'KM2000',
	'BP_KNT76_KESKIN': 'KNT-76',
	'BP_KPVT_UB32': 'KPVT / UB-32 Weapon System',
	'BP_Kamaz_5350': 'KamAZ-5350',
	'BP_Kord_BTR-D': 'BTR-D Kord 12.7mm HMG',
	'BP_Kord_Cupola_Weapon': 'Kord Cupola 12.7mm HMG',
	'BP_Kord_Cupola_Weapon_T64BM2': 'T-64BM2 Kord Cupola 12.7mm HMG',
	'BP_Kord_Kozak': 'Kozak Kord 12.7mm HMG',
	'BP_Kord_Safir_Weapon': 'Safir Kord 12.7mm HMG',
	'BP_Kord_Tigr': 'Tigr Kord 12.7mm HMG',
	'BP_Kornet_Proj2': '9M133 Kornet Missile',
	'BP_Ks23_Shotgun_supermod': 'KS-23',
	'BP_L109A1Frag': 'L109A1 Fragmentation Grenade',
	'BP_L110A2': 'L110A2',
	'BP_L110A2_SUSAT': 'L110A2 + SUSAT',
	'BP_L119A1_ET552_Foregrip': 'L119A1 + ET552 + Foregrip',
	'BP_L128A1_Shotgun_supermod': 'L128A1',
	'BP_L129A1_Optic': 'L129A1',
	'BP_L131A1': 'L131A1 General Service Pistol',
	'BP_L22A2_Foregrip': 'L22A2 + Foregrip',
	'BP_L22A2_SUSAT_Foregrip': 'L22A2 + SUSAT + Foregrip ',
	'BP_L30A1_AP': 'L30A1 120mm Armor Piercing',
	'BP_L55_AP': 'L55 120mm Armor Piercing',
	'BP_L55_HEAT': 'L55 120mm HEAT',
	'BP_L55_coax': 'L55 Coaxial Machine Gun',
	'BP_L7A2': 'L7A2',
	'BP_L85A2': 'L85A2',
	'BP_L85A2AG36_LDS_Rifle': 'L85A2 L123A2 + LDS',
	'BP_L85A2AG36_LDS_UGL_HE': 'L123A2 High Explosive',
	'BP_L85A2AG36_LDS_UGL_Smoke': 'L123A2 Smoke (White)',
	'BP_L85A2AG36_LDS_UGL_Smoke_Blue': 'L123A2 Smoke (Blue)',
	'BP_L85A2AG36_LDS_UGL_Smoke_Red': 'L123A2 Smoke (Red)',
	'BP_L85A2_1mag': 'L85A2',
	'BP_L85A2_Grippod': 'L85A2 + Grippod',
	'BP_L85A2_LDS': 'L85A2 + LDS',
	'BP_L85A2_LDS_Grippod': 'L85A2 + LDS + Grippod',
	'BP_L85A2_M150': 'L85A2 + M150',
	'BP_L85A2_M150_Foregrip': 'L85A2 + ACOG + Foregrip Bipod',
	'BP_L85A2_SUSAT': 'L85A2 + SUSAT',
	'BP_L85A2_SUSAT_Grippod': 'L85A2 + SUSAT + Grippod',
	'BP_L86A2LSW_SUSAT': 'L86A2 LSW + SUSAT',
	'BP_L94A1_coax': 'L94A1 7.62mm Coaxial Machine Gun',
	'BP_LAV2_Coyote_CRF': 'LAV2 Coyote CRF',
	'BP_LeeEnfieldNo4': 'Lee-Enfield No.4 Mk I',
	'BP_LeeEnfieldNo4_Sniper': 'Lee-Enfield No.4 MkI + No.32',
	'BP_M1014_Benelli_Shotgun': 'Benelli M4 Romeo 3',
	'BP_M1014_Shotgun_supermod': 'M1014 JSCS',
	'BP_M110_Optic': 'M110 SASS',
	'BP_M110_Optic_Suppressed': 'M110 SASS + Suppressor',
	'BP_M1117_M2': 'M1117 ASV M2 .50 cal HMG',
	'BP_M1126_CROWS_M2': 'M1126 Stryker CROWS M2 .50 cal HMG',
	'BP_M1126_CROWS_M240': 'M1126 Stryker CROWS M240 7.62mm MG',
	'BP_M1126_Woodland': 'M1126 Stryker',
	'BP_M113A2T_TLF_Logi_Obliterate': 'TLF M113A2T Logistics Obliterated',
	'BP_M1151_TOW_WPMC': 'M1151 TOW WPMC',
	'BP_M1151_Technical_DShK_Shield': 'M1151 Technical DShK Shielded HMG',
	'BP_M1151_WPMC': 'M1151 HMMWV WPMC',
	'BP_M134_DoorGun': 'M134 Minigun Door Gun',
	'BP_M134_Weapon_CPV': 'M134 Minigun CPV',
	'BP_M136AT4': 'M136 AT4',
	'BP_M14': 'M14',
	'BP_M14_M1A': 'M1A',
	'BP_M14_M68': 'M14 + M68',
	'BP_M14_M68_M1A': 'M1A + M68',
	'BP_M16A2': 'M16A2',
	'BP_M16A2M203_Rifle': 'M16A2 M203',
	'BP_M16A2M203_Rifle_SuperMod': 'M16A2 + M203',
	'BP_M16A2M203_UGL_HE': 'M203 High Explosive',
	'BP_M16A2M203_UGL_HE_3mags': 'M203 High Explosive',
	'BP_M16A2M203_UGL_HE_SuperMod': 'M203 High Explosive',
	'BP_M16A2M203_UGL_Smoke': 'M203 Smoke',
	'BP_M16A2M203_UGL_Smoke_Blue': 'M203 Smoke Blue',
	'BP_M16A2M203_UGL_Smoke_Blue_SuperMod': 'M203 Smoke Blue',
	'BP_M16A2M203_UGL_Smoke_Red': 'M203 Smoke Red',
	'BP_M16A2M203_UGL_Smoke_Red_SuperMod': 'M203 Smoke Red',
	'BP_M16A2M203_UGL_Smoke_SuperMod': 'M203 Smoke',
	'BP_M16A2_Optic': 'M16A2 + 3x20 Optic',
	'BP_M16A2_Optic_Semi': 'AR15 + 3x20 Optic',
	'BP_M16A4M203_M150_UGL_HE': 'M203 High Explosive',
	'BP_M16A4M203_M150_UGL_HE_MEE': 'M203 High Explosive',
	'BP_M16A4M203_M150_UGL_Smoke': 'M203 Smoke (White)',
	'BP_M16A4M203_M150_UGL_Smoke_Blue': 'M203 Smoke (Blue)',
	'BP_M16A4M203_M150_UGL_Smoke_Blue_MEE': 'M203 Smoke (Blue)',
	'BP_M16A4M203_M150_UGL_Smoke_MEE': 'M203 Smoke (White)',
	'BP_M16A4M203_M150_UGL_Smoke_Red': 'M203 Smoke (Red)',
	'BP_M16A4M203_M150_UGL_Smoke_Red_MEE': 'M203 Smoke (Red)',
	'BP_M16A4M203_Rifle': 'M16A4 M203',
	'BP_M16A4M203_Rifle_M150': 'M16A4 M203 + M150',
	'BP_M16A4M203_UGL_HE': 'M203 High Explosive',
	'BP_M16A4M203_UGL_HE_3rounds': 'M203 High Explosive',
	'BP_M16A4M203_UGL_Smoke': 'M203 Smoke (White)',
	'BP_M16A4M203_UGL_Smoke_Blue': 'M203 Smoke (Blue)',
	'BP_M16A4M203_UGL_Smoke_Red': 'M203 Smoke (Red)',
	'BP_M16A4_1mag': 'M16A4 + Irons',
	'BP_M16A4_Foregrip': 'M16A4 + Foregrip',
	'BP_M16A4_M150': 'M16A4 + M150',
	'BP_M16A4_M150_Foregrip': 'M16A4 + M150 + Foregrip',
	'BP_M16A4_Semi': 'AR15',
	'BP_M16_Wormpool_EXPS': 'M16 Wormpool + EXPS + Foregrip',
	'BP_M16_Wormpool_Ironsights': 'M16 Wormpool + Foregrip',
	'BP_M16_Wormpool_Ironsights_Cmag': 'M16 Wormpool + C-mag',
	'BP_M16_Wormpool_M150': 'M16 Wormpool + M150 + Foregrip',
	'BP_M16_Wormpool_M150_Semi': 'AR15 Wormpool + M150 + Foregrip',
	'BP_M16_Wormpool_Meupold': 'M16 Wormpool + Meupold',
	'BP_M16_Wormpool_Meupold_Semi': 'AR15 Wormpool + Meupold',
	'BP_M16_Wormpool_T800': 'M16 Wormpool + T800 + Foregrip',
	'BP_M17MHS': 'M17',
	'BP_M18': 'M18',
	'BP_M1911_2mags': 'M1911',
	'BP_M1917': 'M1917',
	'BP_M1A1_FLEX_M2': 'M1A1 FLEX M2 .50 cal HMG',
	'BP_M1A1_USMC_Cmdr_M2': 'M1A1 USMC Commander M2 .50 cal HMG',
	'BP_M1A1_USMC_Cmdr_M2_Woodland': 'M1A1 USMC Commander M2 .50 cal HMG (Woodland)',
	'BP_M1A1_USMC_Woodland': 'M1A1 Abrams USMC (Woodland)',
	'BP_M1Carbine_Ironsights': 'M1 Carbine',
	'BP_M21_Meupold': 'M21 + Meupold',
	'BP_M240': 'M240B',
	'BP_M240_M145': 'M240B + M145',
	'BP_M240_MGO': 'M240G + MGO',
	'BP_M249_Classic': 'M249',
	'BP_M249_Pip_M145': 'M249 PIP + M145',
	'BP_M249_Pip_M68': 'M249 PIP + M68',
	'BP_M249_Pip_SDO': 'M249 PIP + SDO',
	'BP_M256A1_AP': 'M256A1 120mm Armor Piercing',
	'BP_M256A1_AP_ADF': 'M256A1 120mm Armor Piercing (ADF)',
	'BP_M256A1_HEAT': 'M256A1 120mm HEAT',
	'BP_M256A1_coax': 'M256A1 Coaxial Machine Gun',
	'BP_M256A1_coax_ADF': 'M256A1 Coaxial Machine Gun (ADF)',
	'BP_M27': 'M27 IAR',
	'BP_M27_Bipod': 'M27 IAR + Bipod',
	'BP_M27_Optic': 'M27 IAR + SDO',
	'BP_M27_Optic_Bipod': 'M27 IAR + SDO + Bipod',
	'BP_M2_Technical': 'Technical M2 .50 cal HMG',
	'BP_M320_HE': 'M320 High Explosive',
	'BP_M320_HE_SuperMod': 'M320 GLM HEDP',
	'BP_M320_Smoke_Blue_SuperMod': 'M320 GLM Smoke Marker White',
	'BP_M320_Smoke_Red_SuperMod': 'M320 GLM Smoke Marker White',
	'BP_M320_Smoke_White': 'M320 Smoke (White)',
	'BP_M320_Smoke_White_SuperMod': 'M320 GLM Smoke Marker White',
	'BP_M38_DMR_Optic': 'M38',
	'BP_M39_Optic': 'M39 EMR + M8541',
	'BP_M3MAAWS_HEAT': 'M3 MAAWS (FFV551 HEAT)',
	'BP_M3MAAWS_Heat_3mags': 'M3 MAAWS (FFV551 HEAT)',
	'BP_M3MAAWS_Smoke_2mags': 'M3 MAAWS (FFV469B Smoke)',
	'BP_M3MAAWS_Tandem': 'M3 MAAWS (FFV751 Tandem)',
	'BP_M3MDFSW_Heat': 'M3 MDFSW (FFV551 HEAT)',
	'BP_M3MDFSW_Tandem': 'M3 MDFSW (FFV751 Tandem)',
	'BP_M4': 'M4',
	'BP_M4A1M203_M150_UGL_HE_MEE': 'M203 High Explosive Dual Purpose',
	'BP_M4A1M203_M150_UGL_Smoke_Blue_MEE': 'M203 Smoke Marker Blue',
	'BP_M4A1M203_M150_UGL_Smoke_MEE': 'M203 Smoke Marker White',
	'BP_M4A1M203_M150_UGL_Smoke_Red_MEE': 'M203 Smoke Marker Red',
	'BP_M4A1M203_Rifle_M150_MEE': 'M4 M203 + M150',
	'BP_M4A1M203_Rifle_TA01_MEE': 'M4A1M203 + TA01',
	'BP_M4A1M203_TA01_UGL_HE_MEE': 'M203 High Explosive Dual Purpose',
	'BP_M4A1M203_TA01_UGL_Smoke_Blue_MEE': 'M203 Smoke Marker Blue',
	'BP_M4A1M203_TA01_UGL_Smoke_MEE': 'M203 Smoke Marker White',
	'BP_M4A1M203_TA01_UGL_Smoke_Red_MEE': 'M203 Smoke Marker Red',
	'BP_M4A1_Foregrip': 'M4A1 + Foregrip',
	'BP_M4A1_M150_Foregrip': 'M4A1 + M150 + Foregrip',
	'BP_M4A1_M68_Foregrip': 'M4A1 + M68 + Foregrip',
	'BP_M4B2_M203_M150_UGL_HE': 'M203 HE',
	'BP_M4B2_M203_M150_UGL_Smoke': 'M203 Smoke Marker White',
	'BP_M4B2_M203_M150_UGL_Smoke_Blue': 'M203 Smoke Marker Blue',
	'BP_M4B2_M203_M150_UGL_Smoke_Red': 'M203 Smoke Marker Red',
	'BP_M4B2_M203_Rifle_M150': 'M4B2M203 M150',
	'BP_M4B2_M203_UGL_Smoke_Blue': 'M203 Smoke Marker Blue',
	'BP_M4B2_M203_UGL_Smoke_Red': 'M203 Smoke Marker Red',
	'BP_M4M203_Rifle': 'M4 M203',
	'BP_M4M203_UGL_HE_3rounds': 'M203 High Explosive',
	'BP_M4M203_UGL_Smoke': 'M203 Smoke (White)',
	'BP_M4M203_UGL_Smoke_Blue': 'M203 Smoke (Blue)',
	'BP_M4M203_UGL_Smoke_Red': 'M203 Smoke (Red)',
	'BP_M4_1Mag': 'M4',
	'BP_M4_4Mags': 'M4',
	'BP_M4_Carryhandle': 'M4',
	'BP_M4_Carryhandle_4Mags': 'M4',
	'BP_M4_Carryhandle_Foregrip': 'M4 + Foregrip',
	'BP_M4_Carryhandle_Recruit': 'M4',
	'BP_M4_Classic_Fajr': 'Fajr 224',
	'BP_M4_Classic_M68': 'M4 + M68',
	'BP_M4_Classic_M68_Semi': 'AR15 + M68',
	'BP_M4_Classic_Semi': 'AR15',
	'BP_M4_Foregrip': 'M4 + Foregrip',
	'BP_M4_M150': 'M4 + M150',
	'BP_M4_M150_Foregrip': 'M4 + M150 + Foregrip',
	'BP_M4_M203_IDF_M203_UGL_Smoke_Blue': 'M203 Smoke Marker Blue',
	'BP_M4_M203_IDF_UGL_HE': 'M203 HE',
	'BP_M4_M203_IDF_UGL_Smoke': 'M203 Smoke Marker White',
	'BP_M4_M203_IDF_UGL_Smoke_Red': 'M203 Smoke Marker Red',
	'BP_M4_M203_M21_UGL_HE': 'M203 HE',
	'BP_M4_M203_M21_UGL_Smoke': 'M203 Smoke Marker White',
	'BP_M4_M203_M21_UGL_Smoke_Red': 'M203 Smoke Marker Red',
	'BP_M4_M203_Rifle_M21': 'M4A1 M21 M203',
	'BP_M4_M21_M203_UGL_Smoke_Blue': 'M203 Smoke Marker Blue',
	'BP_M4_M68': 'M4 + M68',
	'BP_M4_M68_Foregrip': 'M4 + M68 + Foregrip',
	'BP_M4_SimonOffense_EXPS': 'M4 Simon Offense + EXPS',
	'BP_M4_SimonOffense_T800': 'M4 Simon Offense + T800 + Foregrip',
	'BP_M4_Wormpool_EXPS': 'M4 Wormpool + EXPS + Foregrip',
	'BP_M4_Wormpool_Ironsights': 'M4 Wormpool + Foregrip',
	'BP_M4_Wormpool_M150': 'M4 Wormpool + M150 + Foregrip',
	'BP_M4_Wormpool_T800': 'M4 Wormpool + T800',
	'BP_M4_Wormpool_T800_Semi': 'AR15 Wormpool + T800',
	'BP_M60T_M85': 'M60T M85 .50 cal HMG',
	'BP_M67Frag': 'M67 Fragmentation Grenade',
	'BP_M68A2_AP': 'M68A2 105mm Armor Piercing',
	'BP_M68A2_coax': 'M68A2 Coaxial Machine Gun',
	'BP_M72A5_Rocket_Proj': 'M72A5 LAW Rocket',
	'BP_M72A6_Rocket_Proj': 'M72A6 LAW Rocket',
	'BP_M72A7': 'M72A7 LAW',
	'BP_M72A7_2Rounds': 'M72A7 LAW',
	'BP_M72A7_LASM': 'L72A9 LASM',
	'BP_M72A7_M72A5': 'M72A5-C1',
	'BP_M72A7_M72A5_2mags': 'M72A5-C1',
	'BP_M72A7_SRAAW': 'M72 SRAAW',
	'BP_M79_Parent_SuperMod': 'M79',
	'BP_M870_ADF': 'M870',
	'BP_M939Truck_Woodland_Destroyed': 'M939 Truck Destroyed (Woodland)',
	'BP_M939Truck_Woodland_Obliterate_USMC': 'M939 Truck USMC Obliterated (Woodland)',
	'BP_M9A1': 'M9A1',
	'BP_M9Bayonet': 'M9 Bayonet',
	'BP_MG253_AP': 'MG253 120mm Armor Piercing',
	'BP_MG253_Frag': 'MG253 120mm Fragmentation Round',
	'BP_MG253_coax': 'MG253 Coaxial Machine Gun',
	'BP_MG3': 'MG3',
	'BP_MG3_Specter': 'MG3 + Specter',
	'BP_MG4_ZF': 'MG4 + ZF',
	'BP_MGL_HE': 'MKE MGL High Explosive',
	'BP_MGL_HE_SuperMod': 'MKE MGL High Explosive',
	'BP_MGL_Smoke': 'MKE MGL White (Smoke)',
	'BP_MGL_Smoke_SuperMod': 'MKE MGL White (Smoke)',
	'BP_MI8': 'Mi-8 Helicopter',
	'BP_MI8_AFU': 'Mi-8 AFU',
	'BP_MP443': 'MP-443 Grach',
	'BP_MP443_5Mags': 'MP-443 Grach',
	'BP_MP5A3': 'MP5A3',
	'BP_MP5A3_4mags': 'MP5A3',
	'BP_MP5A3_Crewman_SuperMod': 'MP5A3',
	'BP_MP5A3_T800': 'MP5A3 + T800',
	'BP_MP5A3_T800_4mags': 'MP5A3 + T800',
	'BP_MP5A3_T800_9Mag': 'MP5A3 + T800',
	'BP_MPT55M203_Rifle_A940_MEE': 'MPT55 + M203 + A940',
	'BP_MPT55M20_A940_UGL_HE_MEE': 'M203 High Explosive Dual Purpose',
	'BP_MPT55M20_A940_UGL_Smoke_Blue_MEE': 'M203 Smoke Marker Blue',
	'BP_MPT55M20_A940_UGL_Smoke_MEE': 'M203 Smoke Marker White',
	'BP_MPT55M20_A940_UGL_Smoke_Red_MEE': 'M203 Smoke Marker Red',
	'BP_MPT76': 'MPT-76',
	'BP_MPT76_1Mag': 'MPT-76',
	'BP_MPT76_A940': 'MPT-76 + A940',
	'BP_MPT76_AK40GL_A940_Rifle': 'MPT-76 AK-40GL + A940',
	'BP_MPT76_AK40GL_A940_UGL_HE': 'AK-40GL Fragmentation',
	'BP_MPT76_AK40GL_A940_UGL_Smoke': 'AK-40GL Smoke (White)',
	'BP_MPT76_AK40GL_A940_UGL_Smoke_Blue': 'AK-40GL Smoke (Blue)',
	'BP_MPT76_AK40GL_A940_UGL_Smoke_Red': 'AK-40GL Smoke (Red)',
	'BP_MPT76_AK40GL_Rifle': 'MPT-76 AK-40GL',
	'BP_MPT76_AK40GL_UGL_HE': 'AK-40GL Fragmentation',
	'BP_MPT76_AK40GL_UGL_Smoke': 'AK-40GL Smoke (White)',
	'BP_MPT76_AK40GL_UGL_Smoke_Blue': 'AK-40GL Smoke (Blue)',
	'BP_MPT76_AK40GL_UGL_Smoke_Red': 'AK-40GL Smoke (Red)',
	'BP_MPT76_Foregrip': 'MPT-76 +  Foregrip',
	'BP_MPT76_Foregrip_A940': 'MPT-76 + A940 + Foregrip',
	'BP_MPT76_Foregrip_HNA': 'MPT-76 + HNA + Foregrip',
	'BP_MPT76_HNA': 'MPT-76 + HNA',
	'BP_MPT9': 'MPT9',
	'BP_MTAR_M203_UGL_HE': 'M203 HE Mepro GLS',
	'BP_MTAR_M203_UGL_Smoke_Blue': 'M203 Smoke Blue Mepro GLS',
	'BP_MTAR_M203_UGL_Smoke_Red': 'M203 Smoke Red Mepro GLS',
	'BP_MTAR_UGL_Smoke': 'M203 Smoke Mepro GLS',
	'BP_MTLBM_6MA_GFI': 'MT-LBM 6MA GFI',
	'BP_MTLB_30mm_AP_gun': 'MT-LB 30mm Armor Piercing Gun',
	'BP_MTLB_30mm_AP_gun_Green': 'MT-LB 30mm Armor Piercing Gun (Green)',
	'BP_MTLB_Burn': 'MT-LB Burned',
	'BP_MTLB_GFI_wreck': 'MT-LB GFI Wreck',
	'BP_MTLB_INS': 'INS MT-LB',
	'BP_MTLB_LOGI_IMF': 'IMF MT-LB Logistics',
	'BP_MTLB_LOGI_RUS': 'RUS MT-LB Logistics',
	'BP_MTLB_NSV': 'MT-LB NSV 12.7mm HMG',
	'BP_MTLB_PKT': 'MT-LB PKT 7.62mm Machine Gun',
	'BP_MTLB_PKT_AFU': 'MT-LB AFU PKT 7.62mm Machine Gun',
	'BP_MTLB_PKT_AFU_LowAmmo': 'MT-LB AFU PKT 7.62mm Machine Gun (Low Ammo)',
	'BP_MTLB_PKT_GFI': 'MT-LB GFI PKT 7.62mm Machine Gun',
	'BP_MTLB_PKT_Militia': 'MT-LB Militia PKT 7.62mm Machine Gun',
	'BP_MTLB_PKT_RUS_Desert_LowAmmo': 'MT-LB RUS PKT 7.62mm Machine Gun (Desert, Low Ammo)',
	'BP_MTLB_PKT_RUS_Woodland_LowAmmo': 'MT-LB RUS PKT 7.62mm Machine Gun (Low Ammo)',
	'BP_MTLB_ZU23_MIL': 'Militia MT-LB ZU-23-2',
	'BP_MTLB_Zu23_Obliterate': 'MT-LB ZU-23-2 Obliterated',
	'BP_MTLB_wreck_AFU': 'MT-LB AFU Wreck',
	'BP_MTLB_wreck_green': 'MT-LB Wreck (Green)',
	'BP_Mag58': 'MAG 58',
	'BP_Makarov': 'Makarov PM',
	'BP_Malyuk_1P90_AimpointPro': 'Malyuk 1P90 + Aimpoint PRO',
	'BP_Malyuk_545_EXPS_Foregrip': 'Malyuk (5.45) + EXPS + Foregrip',
	'BP_Malyuk_545_Foregrip': 'Malyuk (5.45) + Foregrip',
	'BP_Malyuk_545_M150': 'Malyuk (5.45) + TA31',
	'BP_Malyuk_545_M150_Foregrip': 'Malyuk (5.45) + TA31 + Foregrip',
	'BP_Malyuk_556_Foregrip': 'Malyuk (5.56) + Foregrip',
	'BP_Malyuk_556_M150_Foregrip': 'Malyuk (5.56) + TA31 + Foregrip',
	'BP_Malyuk_556_Yoloson_Foregrip': 'Malyuk (5.56) + Yoloson + Foregrip',
	'BP_Malyuk_762_Foregrip': 'Malyuk (7.62) + Foregrip',
	'BP_Malyuk_762_M150_Foregrip': 'Malyuk (7.62) + TA31 + Foregrip',
	'BP_Malyuk_762_M68_Foregrip': 'Malyuk (7.62) + M68 + Foregrip',
	'BP_Malyuk_EXPS_G33_Suppressor': 'Malyuk G33+EXPS',
	'BP_Maximi': 'Maximi + Foregrip',
	'BP_Maximi_ET552': 'Maximi + ET552',
	'BP_Maximi_Specter': 'Maximi + Specter',
	'BP_Minimi_Classic': 'Minimi',
	'BP_Minimi_MK3_ELCAN': 'FN Minimi MK3 PARA + ELCAN',
	'BP_Mortarround4': '81mm Mortar Round',
	'BP_Mortarround_120mm': '120mm Mortar Round',
	'BP_Mortarround_120mm_Airburst': '120mm Airburst Mortar Round',
	'BP_Mosin_M1891': 'Mosin Nagant M1891/30',
	'BP_Mosin_M1891_Sniper': 'Mosin Nagant M1891/30 + PU-1',
	'BP_Mosin_M38Carbine': 'Mosin Nagant M38',
	'BP_Mosin_M38Carbine_1Mag': 'Mosin Nagant M38',
	'BP_NLAW': 'NLAW',
	'BP_NLAW_2mags': 'NLAW',
	'BP_OKC-3S': 'OKC-3S',
	'BP_PAMAC50': 'PA MAC 50',
	'BP_PF-98_HE': 'PF98 (DZY-98 HE)',
	'BP_PF-98_HE_2mags': 'PF98 (DZY-98 HE)',
	'BP_PF-98_Tandem': 'PF98 (DZP-98 Tandem)',
	'BP_PF-98_Tandem_2mags': 'PF98 (DZP-98 Tandem)',
	'BP_PKM': 'PKM',
	'BP_PKM_1P29': 'PKM + 1p29',
	'BP_PKM_M150_Tracer': 'PKM + TA31 + Tracer',
	'BP_PKP': 'PKP Pecheneg',
	'BP_PKP_1P78': 'PKP Pecheneg + 1P78',
	'BP_PK_RWS_Gun': 'PK Remote Weapon Station',
	'BP_PLA_Binoculars': 'Type 95 Field Binoculars',
	'BP_PLA_Deployable_TNT_Explosive_Timed': 'PLA Timed TNT Explosive',
	'BP_PMMD63': 'PM md. 63',
	'BP_PMT76': 'PMT-76',
	'BP_PMT76_A940': 'PMT-76 + A940',
	'BP_PMV_Mag58_Weapon': 'PMV MAG58 7.62mm Machine Gun',
	'BP_PMV_RWS_M2': 'PMV RWS M2 .50 cal HMG',
	'BP_PSRL_Heat_2Mag_Wolerine': 'PSRL High Explosive Anti-Tank + HS10C',
	'BP_PSRL_Wolerine_Frag_3Mag': 'PSRL Fragmentation + HS10C',
	'BP_PZF3_DM12_1Round': 'DM12 HEAT',
	'BP_PZF3_DM12_Child': 'DM12 HEAT',
	'BP_PZF3_DM22': 'DM22 Tandem',
	'BP_PZF3_DM32_Child': 'DM32 Bunkerfaust',
	'BP_Ppsh41_Drum': 'PPSh-41 + Drum Mag',
	'BP_Ppsh41_Stick': 'PPSh-41',
	'BP_Projectile_100mm_Frag': '100mm Fragmentation Projectile',
	'BP_Projectile_115mm_HEAT': '115mm HEAT Projectile',
	'BP_Projectile_120mm_HEAT': '120mm HEAT Projectile',
	'BP_Projectile_125mm_Frag': '125mm Fragmentation Projectile',
	'BP_Projectile_125mm_HEAT': '125mm HEAT Projectile',
	'BP_Projectile_155mm_Artillery': '155mm Artillery Shell',
	'BP_Projectile_23mm_HE': '23mm High Explosive Projectile',
	'BP_Projectile_23mm_HE_Green': '23mm High Explosive Projectile (Green)',
	'BP_Projectile_30mm_HE': '30mm High Explosive Projectile',
	'BP_Projectile_30mm_HE_Green': '30mm High Explosive Projectile (Green)',
	'BP_Projectile_30mm_HE_Red': '30mm High Explosive Projectile (Red)',
	'BP_Projectile_30mm_HE_Red_Rarden': '30mm RARDEN High Explosive Projectile (Red)',
	'BP_Projectile_500lb_Bomb': '500 lb Bomb',
	'BP_Projectile_76mm_Frag': '76mm Fragmentation Projectile',
	'BP_Projectile_76mm_HEAT': '76mm HEAT Projectile',
	'BP_Projectile_Hell_Cannon': 'Hell Cannon Projectile',
	'BP_Projectile_RifleGrenade_FNFAL_Frag': 'FN FAL Rifle Grenade (Fragmentation)',
	'BP_Projectile_RifleGrenade_FNFAL_HEAT': 'FN FAL Rifle Grenade (HEAT)',
	'BP_QBU-191_DMR_Optic_QMK-191': 'QBU-191 + QMK-191',
	'BP_QBU-191_DMR_Optic_QMK-191_Suppressor': 'QBU-191 + QMK-191 + Suppressor',
	'BP_QBU-88_Optic': 'QBU-88',
	'BP_QBZ191_Holo': 'QBZ-191 + Holo Sight',
	'BP_QBZ191_Holo_Grippod': 'QBZ-191 + Grip Pod + Holo Sight',
	'BP_QBZ191_IronSights': 'QBZ-191',
	'BP_QBZ191_IronSights_Grippod': 'QBZ-191 + Grip Pod',
	'BP_QBZ191_Optic_QMK171A': 'QBZ-191 + QMK-171A',
	'BP_QBZ191_Optic_QMK171A_Grippod': 'QBZ-191 + Grip Pod + QMK-171A',
	'BP_QBZ192_Holo': 'QBZ-192 + Holo Sight',
	'BP_QBZ192_Holo_Grippod': 'QBZ-192 + Grip Pod + Holo Sight',
	'BP_QBZ192_Holo_Grippod_Suppressor': 'QBZ-192 + Grip Pod + Holo Sight + Suppressor',
	'BP_QBZ192_IronSights': 'QBZ-192',
	'BP_QBZ192_IronSights_4mags': 'QBZ-192',
	'BP_QBZ192_IronSights_Grippod': 'QBZ-192 + Grip Pod',
	'BP_QBZ192_IronSights_Grippod_4mags': 'QBZ-192 + Grip Pod',
	'BP_QBZ192_Optic_QMK171A': 'QBZ-192 + QMK-171A',
	'BP_QBZ192_Optic_QMK171A_Grippod': 'QBZ-192 + Grip Pod + QMK-171A',
	'BP_QBZ192_Optic_QMK171A_Grippod_Suppressor': 'QBZ-192 + Grip Pod + QMK-171A + Suppressor',
	'BP_QBZ95-1': 'QBZ95-1',
	'BP_QBZ95-1_1mag': 'QBZ95-1',
	'BP_QBZ95-1_Holo': 'QBZ95-1 + Holo Sight',
	'BP_QBZ95-1_Holo_4Mags': 'QBZ95-1 + Holo Sight',
	'BP_QBZ95-1_Holo_Tracer': 'QBZ95-1 + Holo Sight',
	'BP_QBZ95-1_Optic': 'QBZ95-1 + YMA600',
	'BP_QBZ95-1_Optic_Tracer': 'QBZ95-1 + YMA600',
	'BP_QBZ95-1_QLG-10_Optic_UGL_HE': 'QLG-10 High Explosive',
	'BP_QBZ95-1_QLG-10_Optic_UGL_Smoke': 'QLG-10 Smoke (White)',
	'BP_QBZ95-1_QLG-10_Optic_UGL_Smoke_Blue': 'QLG-10 Smoke (Blue)',
	'BP_QBZ95-1_QLG-10_Optic_UGL_Smoke_Red': 'QLG-10 Smoke (Red)',
	'BP_QBZ95-1_QLG-10_Rifle': 'QBZ95-1 QLG-10',
	'BP_QBZ95-1_QLG-10_Rifle_Optic': 'QBZ95-1 QLG-10 + YMA600',
	'BP_QBZ95-1_QLG-10_UGL_HE': 'QLG-10 High Explosive',
	'BP_QBZ95-1_QLG-10_UGL_Smoke': 'QLG-10 Smoke (White)',
	'BP_QBZ95-1_QLG-10_UGL_Smoke_Blue': 'QLG-10 Smoke (Blue)',
	'BP_QBZ95-1_QLG-10_UGL_Smoke_Red': 'QLG-10 Smoke (Red)',
	'BP_QBZ95-1_Tracer': 'QBZ95-1',
	'BP_QBZ95B-1': 'QBZ95B-1',
	'BP_QBZ95B-1_4Mag': 'QBZ95B-1',
	'BP_QCW05_Holo_3mags': 'QCW-05 + Holo Sight',
	'BP_QCW05_Holo_Suppressor': 'QCW-05 + Holo Sight + Suppressor',
	'BP_QCW05_IronSights_3mags': 'QCW-05',
	'BP_QCW05_IronSights_Suppressor': 'QCW-05 Suppressed',
	'BP_QJB201_IronSights': 'QJB-201',
	'BP_QJB201_Optic': 'QJB-201 + QMK-204',
	'BP_QJB95-1_LSW': 'QJB95-1',
	'BP_QJB95-1_LSW_Optic': 'QJB95-1 + YMA600',
	'BP_QJY-201_IronSights': 'QJY-201',
	'BP_QJY-201_Optics': 'QJY-201 + QMK-203',
	'BP_QJY-88': 'QJY-88',
	'BP_QJY-88_Optic': 'QJY-88 + YMA95',
	'BP_QJY88_CSK131_Weapon': 'CSK-131 QJY-88 Machine Gun',
	'BP_QJY88_CTM131': 'CTM-131 QJY-88 Machine Gun',
	'BP_QJZ89_CSK131': 'CSK-131 QJZ-89 12.7mm HMG',
	'BP_QJZ89_CTM131': 'CTM-131 QJZ-89 12.7mm HMG',
	'BP_QJZ89_RWS': 'QJZ-89 Remote Weapon Station 12.7mm HMG',
	'BP_QJZ89_RWS_Naval': 'Naval QJZ-89 Remote Weapon Station',
	'BP_QJZ89_Weapon_Lynx8x8': 'Lynx 8x8 QJZ-89 12.7mm HMG',
	'BP_QLZ87_AGL_HEDP_IronSights': 'QLZ-87 AGL High Explosive Dual Purpose',
	'BP_QLZ87_AGL_HEDP_Optic': 'QLZ-87 AGL High Explosive Dual Purpose + YMA-87-35',
	'BP_QNL-95_Bayonet': 'QNL-95 Bayonet',
	'BP_QSZ-92': 'QSZ-92',
	'BP_RGD5Frag': 'RGD-5 Fragmentation Grenade',
	'BP_RGD5Frag_Brown': 'RGD-5 Fragmentation Grenade (Brown)',
	'BP_RGOFrag_Brown': 'RGO Fragmentation Grenade (Brown)',
	'BP_RPD': 'RPD',
	'BP_RPG26': 'RPG-26',
	'BP_RPG26_2mags': 'RPG-26',
	'BP_RPG28': 'RPG-28',
	'BP_RPG28_2mags': 'RPG-28',
	'BP_RPG29': 'RPG-29 (PG-29V Tandem)',
	'BP_RPG29_Optic': 'RPG-29 (PG-29V Tandem)',
	'BP_RPG7V1_Frag_2Mag': 'RPG-7V1 (OG-7V Fragmentation)',
	'BP_RPG7V1_Heat_2Mag': 'RPG-7V1 (PG-7VL HEAT)',
	'BP_RPG7V1_Tandem_2Mag': 'RPG-7V1 (PG-7VR Tandem)',
	'BP_RPG7V2_Frag_2Mag': 'RPG-7v2 (OG-7V Fragmentation)',
	'BP_RPG7V2_Frag_3Mag': 'RPG-7v2 (OG-7V Fragmentation)',
	'BP_RPG7V2_HEAT-PG7VL': 'RPG-7v2 (PG-7VL HEAT)',
	'BP_RPG7V2_Tandem_2mag': 'RPG-7V2 (PG-7VR Tandem)',
	'BP_RPG7_Frag_2Mag': 'RPG-7 (OG-7V Fragmentation)',
	'BP_RPG7_Frag_5Mag': 'RPG-7 (OG-7V Fragmentation)',
	'BP_RPG7_Frag_Proj2': 'RPG-7 Fragmentation Rocket',
	'BP_RPG7_Heat': 'RPG-7 (PG-7VL HEAT)',
	'BP_RPG7_Heat_2Mag': 'RPG-7 (PG-7VL HEAT)',
	'BP_RPG7_Tandem': 'RPG-7 (PG-7VR Tandem)',
	'BP_RPG7_Tandem_2Mag': 'RPG-7 (PG-7VR Tandem)',
	'BP_RPK': 'RPK',
	'BP_RPK74': 'RPK-74',
	'BP_RPK74M': 'RPK-74M',
	'BP_RPK74M_1P78': 'RPK-74M + 1P78',
	'BP_RPK74_1P29': 'RPK-74 + 1P29',
	'BP_RPK74_M150_Pro': 'RPK-74 + TA31',
	'BP_RPK74_Pro': 'RPK-74',
	'BP_RPK_Yoloson': 'RPK + Yoloson',
	'BP_Russian_Baigish_Binoculars': 'Field Binoculars',
	'BP_S5_Proj2': 'S-5 Rocket',
	'BP_S8_Proj2': 'S-8 Rocket',
	'BP_SA330': 'SA330 Puma Helicopter',
	'BP_SA80Bayonet': 'SA80 Bayonet',
	'BP_SKS': 'SKS',
	'BP_SKSTazco_Ironsight': 'SKS TAZCO',
	'BP_SKSTazco_M150': 'SKS  TAZCO + M150',
	'BP_SKSTazco_T800': 'SKS TAZCO + T800',
	'BP_SKS_Bayonet': 'SKS Bayonet',
	'BP_SKS_Bayonet_SuperMod': 'SKS Bayonet',
	'BP_SKS_Optic': 'SKS + PU',
	'BP_SKS_Optic_Bayonet': 'SKS Bayonet',
	'BP_SKS_SG1_Bayonet_SuperMod': 'SKS Bayonet',
	'BP_SMAW_HEAT': 'Mk 153 SMAW (Mk 3 HEDM)',
	'BP_SMAW_HEAT_2mags': 'Mk 153 SMAW (Mk 3 HEDM)',
	'BP_SMAW_SpottingRifle': 'Mk 153 SMAW (Spotting Rifle)',
	'BP_SMAW_Tandem': 'Mk 153 SMAW (Mk 6 HEAA)',
	'BP_SMAW_Tandem_2mags': 'Mk 153 SMAW (Mk 6 HEAA)',
	'BP_SOCP_Knife_ADF': 'SOCP Knife',
	'BP_SOR109T_4mag': 'SOR-109T',
	'BP_SOR109T_HNA': 'SOR-109T + HNA',
	'BP_SOR109T_HNA_4mag': 'SOR-109T + HNA',
	'BP_SOR9': 'SOR-9',
	'BP_SPG9_og9v_Frag_Proj2': 'SPG-9 OG-9V Fragmentation Round',
	'BP_SPG9_pg9v_Heat_Proj2': 'SPG-9 PG-9V HEAT Round',
	'BP_SV98': 'SV-98',
	'BP_SVDM_Optic': 'SVDM',
	'BP_SVD_Optic': 'SVD',
	'BP_Sawnoff_M870_SPM': 'Sawn-off M870',
	'BP_Scimitar_Rarden_AP_Woodland': 'Scimitar RARDEN 30mm Armor Piercing (Woodland)',
	'BP_Soldier_ADF_AutomaticRifleman': 'ADF Automatic Rifleman',
	'BP_Soldier_ADF_Crewman': 'ADF Crewman',
	'BP_Soldier_ADF_Grenadier1': 'ADF Grenadier',
	'BP_Soldier_ADF_HAT': 'ADF Heavy Anti-Tank',
	'BP_Soldier_ADF_LAT': 'ADF Light Anti-Tank',
	'BP_Soldier_ADF_MachineGunner': 'ADF Machine Gunner',
	'BP_Soldier_ADF_Marksman': 'ADF Marksman',
	'BP_Soldier_ADF_Medic': 'ADF Medic',
	'BP_Soldier_ADF_Rifleman1': 'ADF Rifleman',
	'BP_Soldier_ADF_Rifleman2': 'ADF Rifleman',
	'BP_Soldier_ADF_SL_Crewman': 'ADF Squad Leader Crewman',
	'BP_Soldier_ADF_SquadLeader': 'ADF Squad Leader',
	'BP_Soldier_AFU_AutomaticRifleman01': 'AFU Automatic Rifleman',
	'BP_Soldier_AFU_Crewman01': 'AFU Crewman',
	'BP_Soldier_AFU_Engineer01': 'AFU Engineer',
	'BP_Soldier_AFU_Grenadier01': 'AFU Grenadier',
	'BP_Soldier_AFU_HAT02': 'AFU Heavy Anti-Tank',
	'BP_Soldier_AFU_LAT_C90': 'AFU Light Anti-Tank (C90)',
	'BP_Soldier_AFU_LAT_RPG7': 'AFU Light Anti-Tank (RPG-7)',
	'BP_Soldier_AFU_MachineGunner01': 'AFU Machine Gunner',
	'BP_Soldier_AFU_Marksman01': 'AFU Marksman',
	'BP_Soldier_AFU_Medic01': 'AFU Medic',
	'BP_Soldier_AFU_Raider01': 'AFU Raider',
	'BP_Soldier_AFU_Rifleman01': 'AFU Rifleman',
	'BP_Soldier_AFU_Rifleman02': 'AFU Rifleman',
	'BP_Soldier_AFU_Rifleman03': 'AFU Rifleman',
	'BP_Soldier_AFU_SquadLeader01': 'AFU Squad Leader',
	'BP_Soldier_AFU_SquadLeader02': 'AFU Squad Leader',
	'BP_Soldier_BAF_AutomaticRifleman': 'BAF Automatic Rifleman',
	'BP_Soldier_BAF_Crewman1': 'BAF Crewman',
	'BP_Soldier_BAF_Grenadier': 'BAF Grenadier',
	'BP_Soldier_BAF_LAT': 'BAF Light Anti-Tank',
	'BP_Soldier_BAF_Marksman': 'BAF Marksman',
	'BP_Soldier_BAF_Medic': 'BAF Medic',
	'BP_Soldier_BAF_Rifleman1': 'BAF Rifleman',
	'BP_Soldier_BAF_Rifleman2': 'BAF Rifleman',
	'BP_Soldier_BAF_SquadLeader': 'BAF Squad Leader',
	'BP_Soldier_CAF_Arid_Autorifleman': 'CAF Automatic Rifleman',
	'BP_Soldier_CAF_Arid_Crewman': 'CAF Crewman',
	'BP_Soldier_CAF_Arid_Engineer': 'CAF Engineer',
	'BP_Soldier_CAF_Arid_Grenadier': 'CAF Grenadier',
	'BP_Soldier_CAF_Arid_HeavyAntiTank_02': 'CAF Heavy Anti-Tank',
	'BP_Soldier_CAF_Arid_LightAntiTank': 'CAF Light Anti-Tank',
	'BP_Soldier_CAF_Arid_Machinegunner': 'CAF Machine Gunner',
	'BP_Soldier_CAF_Arid_Medic_02': 'CAF Medic',
	'BP_Soldier_CAF_Arid_Rifleman': 'CAF Rifleman',
	'BP_Soldier_CAF_Arid_Rifleman_02': 'CAF Rifleman',
	'BP_Soldier_CAF_Arid_SquadLeader_2': 'CAF Squad Leader',
	'BP_Soldier_CAF_Arid_SquadLeader_3': 'CAF Squad Leader',
	'BP_Soldier_CAF_Autorifleman': 'CAF Automatic Rifleman',
	'BP_Soldier_CAF_Autorifleman_2': 'CAF Automatic Rifleman',
	'BP_Soldier_CAF_HeavyAntiTank': 'CAF Heavy Anti-Tank',
	'BP_Soldier_CAF_HeavyAntiTank_02': 'CAF Heavy Anti-Tank',
	'BP_Soldier_CAF_LightAntiTank': 'CAF Light Anti-Tank',
	'BP_Soldier_CAF_LightAntiTank2': 'CAF Light Anti-Tank',
	'BP_Soldier_CAF_Medic': 'CAF Medic',
	'BP_Soldier_CAF_Medic_2': 'CAF Medic',
	'BP_Soldier_CAF_Pilot_SL': 'CAF Pilot Squad Leader',
	'BP_Soldier_CAF_Rifleman': 'CAF Rifleman',
	'BP_Soldier_CAF_Rifleman_2': 'CAF Rifleman',
	'BP_Soldier_CAF_SquadLeader2': 'CAF Squad Leader',
	'BP_Soldier_GFI_AutomaticRifleman': 'GFI Automatic Rifleman',
	'BP_Soldier_GFI_Engineer': 'GFI Engineer',
	'BP_Soldier_GFI_Grenadier': 'GFI Grenadier',
	'BP_Soldier_GFI_Heavy_AT': 'GFI Heavy Anti-Tank',
	'BP_Soldier_GFI_Light_AT': 'GFI Light Anti-Tank',
	'BP_Soldier_GFI_Marksman': 'GFI Marksman',
	'BP_Soldier_GFI_Medic': 'GFI Medic',
	'BP_Soldier_GFI_Rifleman': 'GFI Rifleman',
	'BP_Soldier_GFI_Rifleman3': 'GFI Rifleman',
	'BP_Soldier_GFI_SquadLeader': 'GFI Squad Leader',
	'BP_Soldier_IMF_AutomaticRifleman': 'IMF Automatic Rifleman',
	'BP_Soldier_IMF_Grenadier': 'IMF Grenadier',
	'BP_Soldier_IMF_HAT_RPG29': 'IMF Heavy Anti-Tank (RPG-29)',
	'BP_Soldier_IMF_LAT': 'IMF Light Anti-Tank',
	'BP_Soldier_IMF_LAT_RPG26': 'IMF Light Anti-Tank (RPG-26)',
	'BP_Soldier_IMF_Machinegunner': 'IMF Machine Gunner',
	'BP_Soldier_IMF_Medic': 'IMF Medic',
	'BP_Soldier_IMF_Rifleman1': 'IMF Rifleman',
	'BP_Soldier_IMF_Rifleman2': 'IMF Rifleman',
	'BP_Soldier_IMF_SL_Crewman': 'IMF Squad Leader Crewman',
	'BP_Soldier_IMF_Scout': 'IMF Scout',
	'BP_Soldier_IMF_SquadLeader': 'IMF Squad Leader',
	'BP_Soldier_INS_HAT_RPG29': 'INS Heavy Anti-Tank (RPG-29)',
	'BP_Soldier_INS_LAT1': 'INS Light Anti-Tank',
	'BP_Soldier_INS_Medic1': 'INS Medic',
	'BP_Soldier_INS_Rifleman1': 'INS Rifleman',
	'BP_Soldier_INS_Rifleman4': 'INS Rifleman',
	'BP_Soldier_INS_Rifleman6': 'INS Rifleman',
	'BP_Soldier_INS_Rifleman7': 'INS Rifleman',
	'BP_Soldier_INS_Rifleman8': 'INS Rifleman',
	'BP_Soldier_INS_Squadleader1': 'INS Squad Leader',
	'BP_Soldier_INS_Squadleader2': 'INS Squad Leader',
	'BP_Soldier_PLANMC_Crewman': 'PLANMC Crewman',
	'BP_Soldier_PLANMC_Engineer': 'PLANMC Engineer',
	'BP_Soldier_PLANMC_HAT': 'PLANMC Heavy Anti-Tank',
	'BP_Soldier_PLANMC_LAT': 'PLANMC Light Anti-Tank',
	'BP_Soldier_PLANMC_Marksman': 'PLANMC Marksman',
	'BP_Soldier_PLANMC_Medic': 'PLANMC Medic',
	'BP_Soldier_PLANMC_Rifleman2': 'PLANMC Rifleman',
	'BP_Soldier_PLANMC_SquadLeader': 'PLANMC Squad Leader',
	'BP_Soldier_PLA_Crewman_Woodland': 'PLA Crewman',
	'BP_Soldier_PLA_Engineer_Woodland': 'PLA Engineer',
	'BP_Soldier_PLA_Grenadier_Woodland': 'PLA Grenadier',
	'BP_Soldier_PLA_LAT_Woodland': 'PLA Light Anti-Tank',
	'BP_Soldier_PLA_MachineGunner_Woodland': 'PLA Machine Gunner',
	'BP_Soldier_PLA_Marksman_Woodland': 'PLA Marksman',
	'BP_Soldier_PLA_Medic_Woodland': 'PLA Medic',
	'BP_Soldier_PLA_Rifleman1_Woodland': 'PLA Rifleman',
	'BP_Soldier_PLA_Rifleman2_Woodland': 'PLA Rifleman',
	'BP_Soldier_PLA_SquadLeader_Winter': 'PLA Squad Leader',
	'BP_Soldier_PLA_SquadLeader_Woodland': 'PLA Squad Leader',
	'BP_Soldier_RU_AutomaticRifleman': 'RUS Automatic Rifleman',
	'BP_Soldier_RU_Crewman': 'RUS Crewman',
	'BP_Soldier_RU_Engineer': 'RUS Engineer',
	'BP_Soldier_RU_Grenadier': 'RUS Grenadier',
	'BP_Soldier_RU_HAT_RPG28': 'RUS Heavy Anti-Tank (RPG-28)',
	'BP_Soldier_RU_LAT': 'RUS Light Anti-Tank',
	'BP_Soldier_RU_LAT_Rpg26': 'RU Light Anti-Tank (RPG-26)',
	'BP_Soldier_RU_Machinegunner': 'RUS Machine Gunner',
	'BP_Soldier_RU_Marksman': 'RUS Marksman',
	'BP_Soldier_RU_Medic': 'RUS Medic',
	'BP_Soldier_RU_Rifleman1': 'RUS Rifleman',
	'BP_Soldier_RU_Rifleman2': 'RUS Rifleman',
	'BP_Soldier_RU_SquadLeader': 'RUS Squad Leader',
	'BP_Soldier_TLF_Engineer_01': 'TLF Engineer',
	'BP_Soldier_TLF_Gendarme_01': 'TLF Gendarme',
	'BP_Soldier_TLF_Grenadier_02': 'TLF Grenadier',
	'BP_Soldier_TLF_LAT_01': 'TLF Light Anti-Tank',
	'BP_Soldier_TLF_Marksman_01': 'TLF Marksman',
	'BP_Soldier_TLF_Medic_01': 'TLF Medic',
	'BP_Soldier_TLF_Medic_02': 'TLF Medic',
	'BP_Soldier_TLF_Rifleman_03': 'TLF Rifleman',
	'BP_Soldier_TLF_SL_01': 'TLF Squad Leader',
	'BP_Soldier_TLF_SL_03': 'TLF Squad Leader',
	'BP_Soldier_USA_AutomaticRifleman_Woodland': 'USA Automatic Rifleman',
	'BP_Soldier_USA_Crewman': 'USA Crewman',
	'BP_Soldier_USA_Grenadier_Woodland': 'USA Grenadier',
	'BP_Soldier_USA_HAT': 'USA Heavy Anti-Tank',
	'BP_Soldier_USA_HAT_Woodland': 'USA Heavy Anti-Tank',
	'BP_Soldier_USA_LAT': 'USA Light Anti-Tank',
	'BP_Soldier_USA_LAT_AT4': 'USA Light Anti-Tank (AT4)',
	'BP_Soldier_USA_LAT_AT4_Woodland': 'USA Light Anti-Tank (AT4)',
	'BP_Soldier_USA_LAT_Woodland': 'USA Light Anti-Tank',
	'BP_Soldier_USA_Machinegunner_Woodland': 'USA Machine Gunner',
	'BP_Soldier_USA_Marksman_Woodland': 'USA Marksman',
	'BP_Soldier_USA_Medic_Woodland': 'USA Medic',
	'BP_Soldier_USA_Rifleman1_Woodland': 'USA Rifleman',
	'BP_Soldier_USA_Rifleman2_Woodland': 'USA Rifleman',
	'BP_Soldier_USA_SL_Pilot_Woodland': 'USA Pilot Squad Leader',
	'BP_Soldier_USA_SquadLeader': 'USA Squad Leader',
	'BP_Soldier_USA_SquadLeader_Woodland': 'USA Squad Leader',
	'BP_Soldier_USMC_HAT_Woodland': 'USMC Heavy Anti-Tank',
	'BP_Soldier_USMC_LAT_M72_Woodland': 'USMC Light Anti-Tank (M72)',
	'BP_Soldier_USMC_Marksman': 'USMC Marksman',
	'BP_Soldier_USMC_Medic_Woodland': 'USMC Medic',
	'BP_Soldier_USMC_Rifleman1': 'USMC Rifleman',
	'BP_Soldier_USMC_Rifleman1_Woodland': 'USMC Rifleman',
	'BP_Soldier_USMC_Rifleman2': 'USMC Rifleman',
	'BP_Soldier_USMC_Rifleman2_Woodland': 'USMC Rifleman',
	'BP_Soldier_USMC_SL_Pilot': 'USMC Pilot Squad Leader',
	'BP_Soldier_USMC_SquadLeader_Woodland': 'USMC Squad Leader',
	'BP_Soldier_VDV_Crewman': 'VDV Crewman',
	'BP_Soldier_VDV_Engineer': 'VDV Engineer',
	'BP_Soldier_VDV_Grenadier': 'VDV Grenadier',
	'BP_Soldier_VDV_LAT': 'VDV Light Anti-Tank',
	'BP_Soldier_VDV_Machinegunner': 'VDV Machine Gunner',
	'BP_Soldier_VDV_Medic': 'VDV Medic',
	'BP_Soldier_VDV_Rifleman1': 'VDV Rifleman',
	'BP_Soldier_VDV_Rifleman2': 'VDV Rifleman',
	'BP_Soldier_VDV_SquadLeader': 'VDV Squad Leader',
	'BP_Soldier_VDV_SquadLeader1': 'VDV Squad Leader',
	'BP_Soldiers_CRF_Crewman_01': 'CRF Crewman',
	'BP_Soldiers_CRF_Grenadier_01': 'CRF Grenadier',
	'BP_Soldiers_CRF_HAT_01': 'CRF Heavy Anti-Tank',
	'BP_Soldiers_CRF_HAT_02': 'CRF Heavy Anti-Tank',
	'BP_Soldiers_CRF_LAT_01': 'CRF Light Anti-Tank',
	'BP_Soldiers_CRF_LAT_02': 'CRF Light Anti-Tank',
	'BP_Soldiers_CRF_Marksman_01': 'CRF Marksman',
	'BP_Soldiers_CRF_Medic_01': 'CRF Medic',
	'BP_Soldiers_CRF_Medic_02': 'CRF Medic',
	'BP_Soldiers_CRF_Raider_02': 'CRF Raider',
	'BP_Soldiers_CRF_Rifleman_02': 'CRF Rifleman',
	'BP_Soldiers_CRF_Rifleman_07': 'CRF Rifleman',
	'BP_Soldiers_CRF_Rifleman_08': 'CRF Rifleman',
	'BP_Soldiers_CRF_Rifleman_09': 'CRF Rifleman',
	'BP_Soldiers_CRF_SL_02': 'CRF Squad Leader',
	'BP_Soldiers_CRF_Sapper_01': 'CRF Sapper',
	'BP_Soldiers_CRF_Unarmed_01': 'CRF Unarmed',
	'BP_Soldiers_WPMC_Grenadier_01': 'WPMC Grenadier',
	'BP_Soldiers_WPMC_HAT_01': 'WPMC Heavy Anti-Tank',
	'BP_Soldiers_WPMC_HAT_02': 'WPMC Heavy Anti-Tank',
	'BP_Soldiers_WPMC_LAT_01': 'WPMC Light Anti-Tank',
	'BP_Soldiers_WPMC_LAT_02': 'WPMC Light Anti-Tank',
	'BP_Soldiers_WPMC_LAT_02_Winter': 'WPMC Light Anti-Tank',
	'BP_Soldiers_WPMC_Marskman_03': 'WPMC Marksman',
	'BP_Soldiers_WPMC_Medic_02': 'WPMC Medic',
	'BP_Soldiers_WPMC_Rifleman_01': 'WPMC Rifleman',
	'BP_Soldiers_WPMC_Rifleman_04': 'WPMC Rifleman',
	'BP_Soldiers_WPMC_Rifleman_06': 'WPMC Rifleman',
	'BP_Soldiers_WPMC_Rifleman_07': 'WPMC Rifleman',
	'BP_Soldiers_WPMC_Rifleman_07_Winter': 'WPMC Rifleman',
	'BP_Soldiers_WPMC_SL_04': 'WPMC Squad Leader',
	'BP_Soldiers_WPMC_SL_04_Winter': 'WPMC Squad Leader',
	'BP_Soldiers_WPMC_SL_05': 'WPMC Squad Leader',
	'BP_Soldiers_WPMC_Sapper_02': 'WPMC Sapper',
	'BP_Soviet_Binoculars': 'Field Binoculars',
	'BP_Sprut_RWS_PKT': 'Sprut remote weapon station PKT 7.62mm MG',
	'BP_Surrender': 'Unarmed',
	'BP_T72A_Kord_Cupola_Weapon': 'T-72A Kord Cupola 12.7mm HMG',
	'BP_T72B3': 'T-72B3',
	'BP_T72S_Kord_Cupola_Weapon': 'T-72S Kord Cupola 12.7mm HMG',
	'BP_T90A_Kord_Cupola_Weapon': 'T-90A Kord Cupola 12.7mm HMG',
	'BP_T90A_Kord_Cupola_Weapon_Desert': 'T-90A Kord Cupola 12.7mm HMG (Desert)',
	'BP_TLAV_M2': 'TLAV M2 .50 cal HMG',
	'BP_TLAV_M240': 'TLAV M240 7.62mm Machine Gun',
	'BP_TLAV_M240_Desert': 'TLAV M240 7.62mm Machine Gun (Desert)',
	'BP_TLAV_M2_Desert': 'TLAV M2 .50 cal HMG (Desert)',
	'BP_TOW_Proj': 'TOW Missile',
	'BP_TT33': 'TT33 Tokarev',
	'BP_TW_338_SWS': 'Timberwolf',
	'BP_Type56-2_Bayonet': 'Type-56-2 Bayonet',
	'BP_Type56_Bayonet': 'Bayonet',
	'BP_Type86p_Frag': 'Type 86P Fragmentation Grenade',
	'BP_UAR-10_Optic': 'UAR-10 + Optic',
	'BP_UH60': 'UH-60M Black Hawk Helicopter',
	'BP_US_Binoculars': 'Field Binoculars',
	'BP_Ural_375_Logi_INS': 'INS Ural-375 Logistics',
	'BP_Ural_375_Logi_MIL': 'Militia Ural-375 Logistics',
	'BP_VOG17_UZRGM_Frag01': 'VOG-17 UZRGM Fragmentation Grenade',
	'BP_VSS_Optic': 'VSS + Optic',
	'BP_Vector_IV': 'Vector IV',
	'BP_Vz61': 'Vz. 61 Škorpion',
	'BP_Vz61_5mags': 'Vz. 61 Škorpion',
	'BP_WZ551B': 'WZ-551B',
	'BP_WZ551B_QLZ-87': 'WZ-551B QLZ-87 Grenade Launcher',
	'BP_Warrior_762': 'Warrior 7.62mm Coaxial Machine Gun',
	'BP_Warrior_Rarden_AP': 'Warrior RARDEN Armor Piercing',
	'BP_X95_LongBarrel_M5_G33': 'X95 .330 M5 + G33',
	'BP_Z8J': 'Z-8J Helicopter',
	'BP_ZBD04A_2A70_coax': 'ZBD-04A 2A70 Coaxial Machine Gun',
	'BP_ZBD04A_ZPT99_AP': 'ZBD-04A ZPT-99 30mm Armor Piercing',
	'BP_ZBD04A_ZPT99_HEFrag': 'ZBD-04A ZPT-99 30mm HE Fragmentation',
	'BP_ZBD05_QTJ02': 'ZBD-05 QTJ02 Grenade Launcher',
	'BP_ZBD05_ZPT-99_APFSDS': 'ZBD-05 ZPT-99 APFSDS',
	'BP_ZBL08_QTJ02': 'ZBL-08 QTJ02 Grenade Launcher',
	'BP_ZBL08_ZPT-99_APFSDS': 'ZBL-08 ZPT-99 APFSDS',
	'BP_ZPT-98_AP': 'ZPT-98 Armor Piercing',
	'BP_ZPT-98_coax': 'ZPT-98 Coaxial Machine Gun',
	'BP_ZSD_QJZ89': 'ZSD QJZ-89 12.7mm HMG',
	'BP_ZSL92_Type86': 'ZSL-92 Type 86 23mm Cannon',
	'BP_ZSL92_ZPT90_AP': 'ZSL-92 ZPT-90 25mm Armor Piercing',
	'BP_ZTD05_ZPL-98A_AP': 'ZTD-05 ZPL-98A Armor Piercing',
	'BP_ZTD05_coax': 'ZTD-05 Coaxial Machine Gun',
	'BTR-DG_Destroy': 'BTR-DG Destroyed',
	'BTR-D_Destroy': 'BTR-D Destroyed',
	'Bradley_AmmoCook_Woodland': 'Bradley Ammo Cookoff (Woodland)',
	'BritUtilTruck_Desert_Destroyed': 'British Utility Truck Destroyed (Desert)',
	'BritUtilTruck_Destroyed': 'British Utility Truck Destroyed',
	'CPV_Destroyed_Blue': 'CPV Destroyed (Blue)',
	'CTM131_Burn': 'CTM-131 Burned',
	'CTM131_Obliterate': 'CTM-131 Obliterated',
	'Coyote_Destroyed_Woodland': 'Coyote Destroyed (Woodland)',
	'Coyote_M252_AP_Desert': 'Coyote 25mm M242 Armor Piercing (Desert)',
	'Coyote_M252_AP_Woodland': 'Coyote 25mm M242 Armor Piercing',
	'Coyote_M252_HE_Woodland': 'Coyote 25mm M242 High Explosive (Woodland)',
	'FV4034_Knockedout': 'FV4034 Challenger 2 Knocked Out',
	'LAV25_762': 'LAV-25 7.62mm Coaxial Machine Gun',
	'LAV25_762_Woodland': 'LAV-25 7.62mm Coaxial Machine Gun',
	'LAV25_Burn_CRF': 'LAV-25 Burned (CRF)',
	'LAV25_M252_AP': 'LAV-25 25mm M242 Armor Piercing',
	'LAV25_M252_AP_Woodland': 'LAV-25 25mm M242 Armor Piercing',
	'LAV25_M252_HE_Woodland': 'LAV-25 25mm M242 High Explosive',
	'LAV_M252_AP': 'LAV 25mm M242 Armor Piercing',
	'LAV_M252_AP_Desert': 'LAV 25mm M242 Armor Piercing',
	'LPPV_Destroyed': 'LPPV Destroyed',
	'LUVW_Obliterate_turret': 'LUVW Turret Obliterated',
	'M1117_Destroy': 'M1117 ASV Destroyed',
	'M1128_Knockedout_Woodland': 'M1128 Stryker MGS Knocked Out (Woodland)',
	'M1a1_USMC_Burned_Woodland': 'M1A1 Abrams USMC Burned (Woodland)',
	'M1a2_Knockedout_Woodland': 'M1A2 Abrams Knocked Out (Woodland)',
	'MATV_destroyed': 'M-ATV Destroyed',
	'MI8_Destroyed_AFU': 'Mi-8 AFU Destroyed',
	'SA330_Destroyed': 'SA330 Puma Destroyed',
	'Safir_Destroyed': 'Safir Destroyed',
	'Sprut_Burn': 'Sprut Burned',
	'Sprut_Destroy': 'Sprut Destroyed',
	'T72A_IMF_Ammocook': 'T-72A IMF Ammo Cookoff',
	'TLFUtilTruck_Burn_Desert': 'TLF Utility Truck Burned (Desert)',
	'TLFUtilTruck_Destroyed': 'TLF Utility Truck Destroyed',
	'TLFUtilTruck_Obliterate': 'TLF Utility Truck Obliterated',
	'TLFUtilTruck_Obliterate_Desert': 'TLF Utility Truck Obliterated (Desert)',
	'Technical_2Seater_Destroyed': 'Technical 2-Seater Destroyed',
	'Technical_4Seater_destroyed_CRF': 'CRF Technical 4-Seater Destroyed',
	'UH1Y_Destroyed': 'UH-1Y Venom Destroyed',
	'UH60M_Crash': 'UH-60M Black Hawk Crash',
	'UH60M_Destroyed': 'UH-60M Destroyed',
	'WPMC_Technical_2Seater_Destroyed_Black': 'WPMC Technical 2-Seater Destroyed (Black)',
	'ZBL08_Ammocook_Naval': 'ZBL-08 Ammo Cookoff (Naval)',
	'ZBL08_Burn_Naval': 'ZBL-08 Burned (Naval)',
	'ZTD05_Destroy': 'ZTD-05 Destroyed',
	'Zsl-10_Burn_Naval': 'ZSL-10 Burned (Naval)',
	'brdm2_Rus_Burn': 'BRDM-2 RUS Burned',
	'brdm2_wreck_AFU': 'BRDM-2 AFU Wreck',
	'kamaz_5350_destroyed': 'KamAZ-5350 Destroyed',
	'kraz_6322_Grad_destroyed': 'KrAZ-6322 Grad Destroyed',
	'kraz_6322_destroyed': 'KrAZ-6322 Destroyed',
	'lav6_Destroy': 'LAV 6 Destroyed',
	'stryker_Obliterate_Woodland': 'Stryker Obliterated (Woodland)',
	'stryker_destroyed_Woodland': 'Stryker Destroyed (Woodland)',
	'ural375_militia_Obliterate': 'Militia Ural-375 Obliterated',
	'ural375_militia_destroyed': 'Militia Ural-375 Destroyed',
	'ural4320_GFI_Obliterate': 'GFI Ural-4320 Obliterated',
	'ural4320_GFI_destroyed': 'GFI Ural-4320 Destroyed',
	'1_BP_AK103_Carryhandle_3X20': 'AK103 Carry Handle 3X20',
	'1_BP_AK103_MRS': 'AK103 MRS',
	'1_BP_AK103_RU03': 'AK103 RU03',
	'1_BP_AK103_RU03_Foregrip': 'AK103 RU03 Foregrip',
	'1_BP_AK104': 'AK104',
	'1_BP_CTAR_Mars': 'CTAR MARS Optic',
	'1_BP_EF88_Eotech_Grippod': 'EF88 EOTech Grip Pod',
	'1_BP_FRA_Maximi_PARA_Eotech': 'FRA Maximi PARA EOTech',
	'1_BP_Ghoul': 'Ghoul',
	'1_BP_L119A2_10_Eotech552_Suppressor': 'L119A2 10 EOTech 552 Suppressor',
	'1_BP_L119A2_10_HHS1_Suppressor': 'L119A2 10 EOTech HHS I Suppressor',
	'1_BP_L119A2_10_T1_Suppressor': 'L119A2 10 Aimpoint T-1 Suppressor',
	'1_BP_L119A2_10_TA01_Suppressor': 'L119A2 10 ACOG TA01 Suppressor',
	'1_BP_L119A2_14_HHS1_Suppressor': 'L119A2 14 EOTech HHS I Suppressor',
	'1_BP_L119A2_14_Razor_Foregrip_Suppressor': 'L119A2 14 Vortex Razor Foregrip Suppressor',
	'1_BP_M16a1_Katsar_M21_IDF': 'M16a1 Katsar M21 IDF',
	'1_BP_M2010_Mk4_Suppressor': 'M2010 Mk4 Suppressor',
	'1_BP_MPT55_A940': 'MPT55 A940 Optic',
	'1_BP_MPT55_A940_Foregrip': 'MPT55 A940 Optic Foregrip',
	'1_BP_Malyuk_EXPS_Suppressor': 'Malyuk EOTech EXPS Suppressor',
	'1_BP_PGM_HECATE_Kahles': 'PGM HECATE Kahles Optic',
	'1_BP_QBU-88_Kahles': 'QBU 88 Kahles Optic',
	'1_BP_SCAR-H_PR_SB': 'SCAR H Precision Rifle Short Barrel',
	'1_BP_SVU_PSO': 'SVU PSO',
	'1_BP_Type56-2': 'Type56 2',
	'1_BP_VHS_CompM2_Magnifer_Grip_ANPEQ_LB': 'VHS Aimpoint CompM2 Magnifier Grip AN/PEQ LB',
	'1_BP_X95_LongBarrel_M150': 'X95 Long Barrel ACOG M150',
	'1_BP_X95_M21_M203_Rifle': 'X95 M21 M203 Rifle',
	'1_BP_X95_M21_MidBarrel': 'X95 M21 Mid Barrel',
	'1_BP_X95_M21_ShortBarrel': 'X95 M21 Short Barrel',
	'2a6_Burned': '2a6 Burned',
	'2a6_Knockedout': '2a6 Knocked Out',
	'AAVP7A1_Burn': 'AAVP7A1 Burned',
	'AAVP7A1_Burn_Woodland': 'AAVP7A1 Burned Woodland',
	'AAVP7A1_Destroy': 'AAVP7A1 Destroyed',
	'AH-1Z_Destroyed': 'AH 1Z Destroyed',
	'AH-64D_USA_Destroyed': 'AH 64D USA Destroyed',
	'ASLAV_destroyed': 'ASLAV Destroyed',
	'AUS_Utility_Truck_Burn': 'AUS Utility Truck Burned',
	'BFV_M252_AP': 'BFV M252 Armor Piercing',
	'BMD4M_Ammocook': 'BMD4M Ammo Cookoff',
	'BMD4M_Ammocook_Desert': 'BMD4M Ammo Cookoff Desert',
	'BMD4M_Burn': 'BMD4M Burned',
	'BMD4M_Destroyed': 'BMD4M Destroyed',
	'BMD4M_Destroyed_Desert': 'BMD4M Destroyed Desert',
	'BMP1AM_Destroy': 'BMP1AM Destroyed',
	'BMP1AM_Destroy_Desert': 'BMP1AM Destroyed Desert',
	'BMP1TS_Ammocook_AFU': 'BMP1TS Ammo Cookoff AFU',
	'BMP1TS_Destroy_AFU': 'BMP1TS Destroyed AFU',
	'BMP1_Ammocook': 'BMP1 Ammo Cookoff',
	'BMP1_Destroy_MIL': 'BMP1 Destroyed Militia',
	'BMP1_GFI_Destroy': 'BMP1 GFI Destroyed',
	'BMP2_Ammocook': 'BMP2 Ammo Cookoff',
	'BMP2_Ammocook_AFU': 'BMP2 Ammo Cookoff AFU',
	'BMP2_Ammocook_IMF': 'BMP2 Ammo Cookoff IMF',
	'BMP2_Burn_IMF': 'BMP2 Burned IMF',
	'BMP2_Destroy_Desert': 'BMP2 Destroyed Desert',
	'BMP2_Destroy_IMF': 'BMP2 Destroyed IMF',
	'BMP2_GFI_Destroy': 'BMP2 GFI Destroyed',
	'BP_2A46M_Frag': '2A46M Fragmentation',
	'BP_2A46M_HEAT': '2A46M HEAT',
	'BP_2A46_Frag': '2A46 Fragmentation',
	'BP_2A46_T72A_HEAT': '2A46 T72A HEAT',
	'BP_2A46_T72S_AP': '2A46 T72S Armor Piercing',
	'BP_2A6_C6_Loaders_Weapon': '2A6 C6 Loaders Weapon',
	'BP_50Cal': '.50 cal HMG',
	'BP_50Cal_LUVW': '.50 cal HMG LUVW',
	'BP_AAVP7A1': 'AAVP7A1 Amphibious APC',
	'BP_AAVP7A1_M2': 'AAVP7A1 M2 .50 cal HMG',
	'BP_AAVP7A1_Woodland': 'AAVP7A1 Amphibious APC (Woodland)',
	'BP_AAVP7A1_Woodland_Logi': 'AAVP7A1 Logistics APC (Woodland)',
	'BP_ACV-15': 'ACV-15 APC',
	'BP_ACV-15_Desert': 'ACV-15 APC (Desert)',
	'BP_ACV_762': 'ACV 7.62mm Coaxial Machine Gun',
	'BP_AC_58_Proj': 'AC 58 Projectile',
	'BP_AH-1Z_2xM260': 'AH 1Z 2x M260',
	'BP_AH-64D_2xM260': 'AH 64D 2x M260',
	'BP_AMX-10-RCR_CE': 'AMX 10 RCR CE',
	'BP_AMX10_ANF1_CE': 'AMX10 ANF1 CE',
	'BP_AMX10_OE_CE': 'AMX10 OE CE',
	'BP_AMX10_OFL_CE': 'AMX10 OFL CE',
	'BP_APAV_F2_Proj': 'APAV F2 Projectile',
	'BP_AT4_HighPenetration_Rocket_Proj2': 'AT4 High Penetration Rocket Projectile',
	'BP_AUS_M1A1': 'AUS M1A1',
	'BP_Armored_Ural_375_Logi_MIL': 'Armored Ural 375 Logistics Militia',
	'BP_Aussie_Util_Truck': 'Australian Util Truck',
	'BP_Avenger_50cal_Weapon_Desert': 'Avenger 50cal Weapon Desert',
	'BP_BFV_762_Woodland': 'BFV 7.62mm Woodland',
	'BP_BFV_Woodland': 'BFV Woodland',
	'BP_BM21Grad_IMF': 'BM21Grad IMF',
	'BP_BM21Grad_Weapon_AFU_Kraz': 'BM21Grad Weapon AFU Kraz',
	'BP_BMP1AM': 'BMP1AM',
	'BP_BMP1AM_Desert': 'BMP1AM Desert',
	'BP_BMP1TS_AFU': 'BMP1TS AFU',
	'BP_BMP1TS_KT762': 'BMP1TS KT-7.62mm',
	'BP_BMP1TS_ZTM1_HE': 'BMP1TS ZTM1 High Explosive',
	'BP_BMP1_AFU': 'BMP1 AFU',
	'BP_BMP1_INS': 'BMP1 INS',
	'BP_BMP1_MIL': 'BMP1 Militia',
	'BP_BMP2M_2A42_HE': 'BMP2M 2A42 High Explosive',
	'BP_BMP2M_PKT': 'BMP2M PKT',
	'BP_BMP2_AFU': 'BMP2 AFU',
	'BP_BMP2_AFU_2A42_HE': 'BMP2 AFU 2A42 High Explosive',
	'BP_BMP2_AFU_PKT': 'BMP2 AFU PKT',
	'BP_BMP3M': 'BMP3M',
	'BP_BMP3M_2A70_HEFrag': 'BMP3M 2A70 High Explosive Fragmentation',
	'BP_BMP3M_2A70_coax': 'BMP3M 2A70 Coaxial Machine Gun',
	'BP_BMP3M_2A72_HE': 'BMP3M 2A72 High Explosive',
	'BP_BMP3M_BowGun_PKT': 'BMP3M Bow Gun PKT',
	'BP_BMP3M_Desert': 'BMP3M Desert',
	'BP_BMP3M_Destroy': 'BMP3M Destroyed',
	'BP_BRDM-2L1_AFU': 'BRDM 2L1 AFU',
	'BP_BRDM-2_Desert_MEINS': 'BRDM 2 Desert ME INS',
	'BP_BRDM-2_MEIMF': 'BRDM 2 ME IMF',
	'BP_BRDM2_GFI_UB32': 'BRDM2 GFI UB-32 Rocket Pod',
	'BP_BRDM2_INS_PKT': 'BRDM-2 INS PKT Machine Gun',
	'BP_BRDM2_KPVT': 'BRDM-2 KPVT Heavy Machine Gun',
	'BP_BRDM2_PKT': 'BRDM-2 PKT Machine Gun',
	'BP_BTR-ZD': 'BTR ZD',
	'BP_BTR4_AFU': 'BTR4 AFU',
	'BP_BTR4_KT762': 'BTR-4 KT-7.62mm Coaxial Machine Gun',
	'BP_BTR80_Militia_KPVT': 'BTR80 Militia KPVT',
	'BP_BTR80_Militia_PKT': 'BTR80 Militia PKT',
	'BP_BTR80_RUS': 'BTR80 RUS',
	'BP_BTR80_RUS_Desert': 'BTR80 RUS Desert',
	'BP_BTR82A_RUS_2A72_HE': 'BTR82A RUS 2A72 High Explosive',
	'BP_BTRMDM_PKT_RWS': 'BTRMDM PKT RWS',
	'BP_BTRMDM_PKT_RWS_Desert': 'BTRMDM PKT RWS Desert',
	'BP_CH146': 'CH146',
	'BP_CH146_Desert': 'CH146 Desert',
	'BP_CH146_Raven': 'CH146 Raven',
	'BP_CN120_AP': 'CN120 Armor Piercing',
	'BP_CN120_AP_Desert': 'CN120 Armor Piercing Desert',
	'BP_CROWS_Mag58_IDF': 'IDF CROWS MAG 58 Machine Gun',
	'BP_CTM131': 'CTM131',
	'BP_CTM131_Logistic': 'CTM131 Logistics',
	'BP_CTM131_Logistic_Desert': 'CTM131 Logistics Desert',
	'BP_CTM131_Logistic_Naval': 'CTM131 Logistics Naval',
	'BP_CTM131_QJZ89': 'CTM131 QJZ-89 HMG',
	'BP_CobraRWS_M2': 'Cobra RWS M2 .50 cal HMG',
	'BP_CobraRWS_M2_Desert': 'Cobra RWS M2 .50 cal HMG (Desert)',
	'BP_CobraRWS_M2_IDF': 'IDF Cobra RWS M2 .50 cal HMG',
	'BP_Cobra_II_OpenTurret_M2_Weapon': 'Cobra II Open Turret M2 .50 cal HMG',
	'BP_Coyote_762_Desert': 'Coyote 7.62mm Desert',
	'BP_Cupola_Dshk': 'Cupola DShK HMG',
	'BP_Cupola_QJZ89': 'Cupola QJZ-89 HMG',
	'BP_DShK_Technical': 'DShK HMG Technical',
	'BP_DShK_Technical_Shield': 'DShK HMG Technical Shield',
	'BP_Deployable_CompB_Explosive': 'Composition B Explosive',
	'BP_Deployable_M16Mine': 'M16 Mine',
	'BP_Deployable_MI_AC_PR_F1': 'Deployable MI AC Precision Rifle F1',
	'BP_Deployable_S_Mine': 'S-Mine',
	'BP_Deployable_TNT_600g_Explosive': '600g TNT Explosive',
	'BP_EC665_2xTelson12': 'EC665 2x Telson12',
	'BP_EC665_AP_HE_BELT_Parent': 'EC665 Armor Piercing High Explosive BELT',
	'BP_ERYX_Proj': 'ERYX Projectile',
	'BP_EmplacedBGM71TOW': 'Emplaced BGM71TOW',
	'BP_EmplacedDshk': 'Emplaced DShK HMG',
	'BP_EmplacedM2HB_Weapon_Ironsight': 'Emplaced M2HB Weapon Iron Sight',
	'BP_EmplacedQJZ-89': 'Emplaced QJZ-89',
	'BP_EmplacedSPG9Scope': 'Emplaced SPG9Scope',
	'BP_EmplacedType63': 'Emplaced Type63',
	'BP_EmplacedUB32': 'Emplaced UB-32 Rocket Pod',
	'BP_Emplaced_ZU23-2_Antiaircannon_Weapon': 'Emplaced ZU-23-2 Antiaircannon Weapon',
	'BP_Emplaced_ZU23-2_Antiaircannon_Weapon_Deployable': 'Emplaced ZU-23-2 Antiaircannon Weapon Deployable',
	'BP_Emplaced_ZU23-2_Antiaircannon_Weapon_INS': 'Emplaced ZU-23-2 Antiaircannon Weapon INS',
	'BP_FV107_Woodland': 'FV107 Woodland',
	'BP_FV4034_Woodland': 'FV4034 Woodland',
	'BP_FV432_M2_RWS': 'FV432 M2 .50 cal HMG RWS',
	'BP_FV432_M2_RWS_Woodland': 'FV432 M2 .50 cal HMG RWS Woodland',
	'BP_FV432_woodland': 'FV432 woodland',
	'BP_FV510UA_Woodland': 'FV510UA Woodland',
	'BP_FV510_Woodland': 'FV510 Woodland',
	'BP_GBC_Destroy': 'GBC Destroyed',
	'BP_GBU_Proj': 'GBU Guided Bomb',
	'BP_GPMG': 'GPMG',
	'BP_GPMG_Woodland': 'GPMG Woodland',
	'BP_GR_MA_DF_F1': 'GR MA DF F1',
	'BP_Ghillie_Bark': 'Ghillie Bark',
	'BP_HEMTT_IDF_Obliterate': 'HEMTT IDF Obliterated',
	'BP_HJ73_Proj2': 'HJ73 Projectile',
	'BP_HescoWall_PLA': 'Hesco Wall PLA',
	'BP_HescoWall_RGF_Desert': 'Hesco Wall RGF Desert',
	'BP_Hydra70_Proj2': 'Hydra 70mm Rocket',
	'BP_Hydra_CAS_Proj_Tiger': 'Tiger CAS Hydra Rocket',
	'BP_IFV25_762': 'IFV25 7.62mm',
	'BP_IRANRG_Rifleman_MEE': 'Iran RG Rifleman MEE',
	'BP_KA-52_2xB-8V20': 'KA 52 2x B-8V20 Rocket Pod',
	'BP_KBA-3_AP': 'KBA 3 Armor Piercing',
	'BP_KBA-3_coax': 'KBA 3 Coaxial Machine Gun',
	'BP_KBA3_Frag': 'KBA3 Fragmentation',
	'BP_KBA3_HEAT': 'KBA3 HEAT',
	'BP_Kamaz-5350_BM21-Grad_Green_VDV': 'Kamaz 5350 BM21 Grad Green VDV',
	'BP_Kozak_Destroy': 'Kozak Destroyed',
	'BP_Kozak_Obliterate': 'Kozak Obliterated',
	'BP_Kraz_6322_Logi': 'Kraz 6322 Logistics',
	'BP_L119A2_14_EXPS_Foregrip': 'L119A2 14 EOTech EXPS Foregrip',
	'BP_L119A2_14_T1G33_Foregrip': 'L119A2 14 Aimpoint T-1 + G33 Foregrip',
	'BP_L119A2_14_TA01_Foregrip': 'L119A2 14 ACOG TA01 Foregrip',
	'BP_L119A2_14_TA01_HK269_Rifle': 'L119A2 14 ACOG TA01 HK269 Rifle',
	'BP_L30A1_HESH': 'L30A1 HESH',
	'BP_L44_AP': 'L44 Armor Piercing',
	'BP_L44_coax': 'L44 Coaxial Machine Gun',
	'BP_LAV25_Woodland': 'LAV25 Woodland',
	'BP_LAV2_Coyote': 'LAV2 Coyote',
	'BP_LAV2_Coyote_Woodland': 'LAV2 Coyote Woodland',
	'BP_LAV6_Woodland': 'LAV6 Woodland',
	'BP_LAV_762': 'LAV 7.62mm',
	'BP_LAV_762_Desert': 'LAV 7.62mm Desert',
	'BP_Leclerc_M2_Coax_Desert': 'Leclerc M2 .50 cal HMG Coaxial Machine Gun Desert',
	'BP_Leclerc_Woodland_Parent': 'Leclerc Woodland',
	'BP_LynxATV_Logistic': 'Lynx ATV Logistics',
	'BP_M1064A3_Woodland_Destroyed': 'M1064A3 Woodland Destroyed',
	'BP_M1128_Woodland': 'M1128 Woodland',
	'BP_M113A2T_Logistics_TLF': 'M113A2T Logistics TLF',
	'BP_M113A3Woodland_Logi_Burn': 'M113A3Woodland Logistics Burned',
	'BP_M113A3_Burn_CRF': 'M113A3 Burned CRF',
	'BP_M113A3_LOGI_Desert_IDF': 'M113A3 Logistics Desert IDF',
	'BP_M113A3_Logistics': 'M113A3 Logistics',
	'BP_M113A3_M2': 'M113A3 M2 .50 cal HMG',
	'BP_M113A3_Woodland_Burn': 'M113A3 Woodland Burned',
	'BP_M113A3_Woodland_Destroyed': 'M113A3 Woodland Destroyed',
	'BP_M113A3_Woodland_Logi_Destroyed': 'M113A3 Woodland Logistics Destroyed',
	'BP_M113A3_Woodland_Obliterate': 'M113A3 Woodland Obliterated',
	'BP_M1151_Light_Woodland': 'M1151 Light Woodland',
	'BP_M1151_Woodland': 'M1151 Woodland',
	'BP_M134_AH-6_Dual_Small': 'M134 AH 6 Dual Small',
	'BP_M134_Weapon': 'M134 Weapon',
	'BP_M1A2_Woodland': 'M1A2 Woodland',
	'BP_M256A1_M2_IDF': 'M256A1 M2 .50 cal HMG IDF',
	'BP_M2_RHIB_Weapon': 'M2 .50 cal HMG RHIB Weapon',
	'BP_M2a1Browning_FV432': 'M2a1Browning FV432',
	'BP_M2a1Browning_FV432_woodland': 'M2a1Browning FV432 woodland',
	'BP_M68A2_HEAT': 'M68A2 HEAT',
	'BP_M939Truck_Desert_Obliterate_USMC': 'M939Truck Desert Obliterated USMC',
	'BP_M939Truck_Woodland_Obliterate': 'M939Truck Woodland Obliterated',
	'BP_MI24V': 'MI24V',
	'BP_MI24_YakB12-7': 'MI24 Yak B12 7',
	'BP_MI28N_B-8V20': 'MI28N B-8V20 Rocket Pod',
	'BP_MILAN_Proj': 'MILAN Projectile',
	'BP_MRH90_Mag58': 'MRH90 Mag58',
	'BP_MTLB_AFU': 'MTLB AFU',
	'BP_MTLB_AFU_Burn': 'MTLB AFU Burned',
	'BP_MTLB_AFU_Obliterate': 'MTLB AFU Obliterated',
	'BP_MTLB_GFI_Obliterate': 'MTLB GFI Obliterated',
	'BP_MTLB_Green_Burn': 'MTLB Green Burned',
	'BP_MTLB_LOGI_AFU': 'MTLB Logistics AFU',
	'BP_MTLB_LOGI_GFI': 'MTLB Logistics GFI',
	'BP_MTLB_VMK_RUS': 'MTLB VMK RUS',
	'BP_MTLB_ZU23_AFU': 'MTLB ZU23 AFU',
	'BP_MTLB_Zu23_wreck': 'MTLB Zu23 Wreck',
	'BP_MTLB_wreck': 'MTLB Wreck',
	'BP_MTLB_wreck_GFI': 'MTLB Wreck GFI',
	'BP_MTLB_wreck_desert': 'MTLB Wreck desert',
	'BP_NSV_RHIB_Weapon': 'NSV RHIB Weapon',
	'BP_OF37': 'OF37',
	'BP_PALINS_LAT02': 'PALINS LAT02',
	'BP_PALINS_Medic': 'PALINS Medic',
	'BP_PARS3': 'PARS3',
	'BP_PARS3_MG3': 'PARS3 MG3',
	'BP_PL127_M2_CE': 'PL127 M2 .50 cal HMG CE',
	'BP_Projectile_105mm_HEAT': '105mm HEAT Projectile',
	'BP_Projectile_120mm_Smoke': 'Projectile 120mm Smoke',
	'BP_Projectile_120mm_Smoke_Arty': '120mm Smoke Artillery Shell',
	'BP_Projectile_30mm_CAS': '30mm CAS Projectile',
	'BP_Projectile_40mm_GPR_Red': 'Projectile 40mm GPR Red',
	'BP_Projectile_Kalibr': 'Kalibr Cruise Missile',
	'BP_RGOFrag_Green': 'RGO Fragmentation Grenade',
	'BP_RSF_DM_Woodland': 'RSF DM Woodland',
	'BP_RSF_HAT_Woodland': 'RSF HAT Woodland',
	'BP_RSF_Medic_Woodland': 'RSF Medic Woodland',
	'BP_RSF_Rifleman01_Woodland': 'RSF Rifleman01 Woodland',
	'BP_RSF_SL01_Woodland': 'RSF SL01 Woodland',
	'BP_RSF_Sniper_Woodland': 'RSF Sniper Woodland',
	'BP_Razorwire_clean_2': 'Razorwire clean 2',
	'BP_Refleks_Proj2': 'Refleks Projectile',
	'BP_SA342M_M621_Desert': 'SA342M M621 Desert',
	'BP_SA342_M621': 'SA342 Gazelle M621 20mm Cannon',
	'BP_SancakRWS_M2': 'Sancak RWS M2 .50 cal HMG',
	'BP_SancakRWS_M2_Desert': 'Sancak RWS M2 .50 cal HMG Desert',
	'BP_SancakRWS_MG3': 'Sancak RWS MG3 Machine Gun',
	'BP_SancakRWS_MG3_Desert': 'Sancak RWS MG3 Machine Gun (Desert)',
	'BP_Scimitar_762': 'Scimitar 7.62mm',
	'BP_Scimitar_762_Woodland': 'Scimitar 7.62mm Woodland',
	'BP_Scimitar_Rarden_AP': 'Scimitar Rarden Armor Piercing',
	'BP_Scimitar_Rarden_HE_Woodland': 'Scimitar Rarden High Explosive Woodland',
	'BP_Soldier_ADF_Engineer': 'Soldier ADF Engineer',
	'BP_Soldier_ADF_Engineer2': 'Soldier ADF Engineer2',
	'BP_Soldier_AFU_HAT01': 'Soldier AFU HAT01',
	'BP_Soldier_AFU_Pilot02': 'Soldier AFU Pilot02',
	'BP_Soldier_AFU_Scout01': 'Soldier AFU Scout01',
	'BP_Soldier_BAF_Engineer': 'Soldier BAF Engineer',
	'BP_Soldier_BAF_HAT': 'Soldier BAF HAT',
	'BP_Soldier_BAF_Machinegunner': 'Soldier BAF Machinegunner',
	'BP_Soldier_BAF_Pilot': 'Soldier BAF Pilot',
	'BP_Soldier_BAF_SLCrewman': 'Soldier BAF SLCrewman',
	'BP_Soldier_BAF_SLPilot': 'Soldier BAF SLPilot',
	'BP_Soldier_CAF_Arid_HeavyAntiTank': 'Soldier CAF Arid Heavy Anti Tank',
	'BP_Soldier_CAF_Arid_Marksman_02': 'Soldier CAF Arid Marksman 02',
	'BP_Soldier_CAF_Arid_Medic': 'Soldier CAF Arid Medic',
	'BP_Soldier_CAF_Engineer': 'Soldier CAF Engineer',
	'BP_Soldier_CAF_Grenadier': 'Soldier CAF Grenadier',
	'BP_Soldier_CAF_Machinegunner': 'Soldier CAF Machinegunner',
	'BP_Soldier_CAF_Marksman': 'Soldier CAF Marksman',
	'BP_Soldier_CAF_Pilot': 'Soldier CAF Pilot',
	'BP_Soldier_CAF_SL_Crewman': 'Soldier CAF Squad Leader Crewman',
	'BP_Soldier_IDF_HAT_02': 'Soldier IDF HAT 02',
	'BP_Soldier_IDF_LAT_02': 'Soldier IDF LAT 02',
	'BP_Soldier_IMF_Crewman': 'Soldier IMF Crewman',
	'BP_Soldier_INS_Crewman1': 'Soldier INS Crewman1',
	'BP_Soldier_INS_LAT2': 'Soldier INS LAT2',
	'BP_Soldier_INS_Rifleman2': 'Soldier INS Rifleman2',
	'BP_Soldier_INS_Sapper': 'Soldier INS Sapper',
	'BP_Soldier_PLANMC_Grenadier': 'Soldier PLANMC Grenadier',
	'BP_Soldier_PLANMC_Rifleman1': 'Soldier PLANMC Rifleman1',
	'BP_Soldier_PLA_AR_Arid': 'Soldier PLA Automatic Rifleman Arid',
	'BP_Soldier_PLA_AR_Woodland': 'Soldier PLA Automatic Rifleman Woodland',
	'BP_Soldier_PLA_Crewman_Arid': 'Soldier PLA Crewman Arid',
	'BP_Soldier_PLA_Engineer_Arid': 'Soldier PLA Engineer Arid',
	'BP_Soldier_PLA_HAT_Arid': 'Soldier PLA HAT Arid',
	'BP_Soldier_PLA_HAT_Woodland': 'Soldier PLA HAT Woodland',
	'BP_Soldier_PLA_HAT_Woodland_SU': 'Soldier PLA HAT Woodland SU',
	'BP_Soldier_PLA_LAT_Arid': 'Soldier PLA LAT Arid',
	'BP_Soldier_PLA_Marksman_Arid': 'Soldier PLA Marksman Arid',
	'BP_Soldier_PLA_Medic_Arid': 'Soldier PLA Medic Arid',
	'BP_Soldier_PLA_Rifleman2_Arid': 'Soldier PLA Rifleman2 Arid',
	'BP_Soldier_PLA_Rifleman_02_Woodland_SU': 'Soldier PLA Rifleman 02 Woodland SU',
	'BP_Soldier_PLA_SquadLeader_01_Woodland_SU': 'Soldier PLA Squad Leader 01 Woodland SU',
	'BP_Soldier_PLA_SquadLeader_Arid': 'Soldier PLA Squad Leader Arid',
	'BP_Soldier_RU_SL_Crewman': 'Soldier RU Squad Leader Crewman',
	'BP_Soldier_RU_SL_Pilot': 'Soldier RU Squad Leader Pilot',
	'BP_Soldier_RU_SL_Pilot_Desert': 'Soldier RU Squad Leader Pilot Desert',
	'BP_Soldier_TLF_Crewman_01': 'Soldier TLF Crewman 01',
	'BP_Soldier_TLF_Grenadier_01': 'Soldier TLF Grenadier 01',
	'BP_Soldier_TLF_LAT_02a': 'Soldier TLF LAT 02a',
	'BP_Soldier_TLF_LAT_03a': 'Soldier TLF LAT 03a',
	'BP_Soldier_TLF_MachineGunner_01': 'Soldier TLF Machine Gunner 01',
	'BP_Soldier_TLF_MachineGunner_02': 'Soldier TLF Machine Gunner 02',
	'BP_Soldier_TLF_Rifleman_01': 'Soldier TLF Rifleman 01',
	'BP_Soldier_TLF_Rifleman_02': 'Soldier TLF Rifleman 02',
	'BP_Soldier_TLF_SL_Crewman_01': 'Soldier TLF Squad Leader Crewman 01',
	'BP_Soldier_USA_AutomaticRifleman': 'Soldier USA Automatic Rifleman',
	'BP_Soldier_USA_Engineer': 'Soldier USA Engineer',
	'BP_Soldier_USA_Engineer_Child': 'Soldier USA Engineer Child',
	'BP_Soldier_USA_Engineer_Woodland': 'Soldier USA Engineer Woodland',
	'BP_Soldier_USA_Grenadier': 'Soldier USA Grenadier',
	'BP_Soldier_USA_Grenadier_Child': 'Soldier USA Grenadier Child',
	'BP_Soldier_USA_Machinegunner': 'Soldier USA Machinegunner',
	'BP_Soldier_USA_Marksman': 'Soldier USA Marksman',
	'BP_Soldier_USA_Medic': 'Soldier USA Medic',
	'BP_Soldier_USA_Rifleman1': 'Soldier USA Rifleman1',
	'BP_Soldier_USA_Rifleman2': 'Soldier USA Rifleman2',
	'BP_Soldier_USA_SL_Crewman': 'Soldier USA Squad Leader Crewman',
	'BP_Soldier_USA_SL_Crewman_Child': 'Soldier USA Squad Leader Crewman Child',
	'BP_Soldier_USA_SL_Pilot_Child': 'Soldier USA Squad Leader Pilot Child',
	'BP_Soldier_USMC_AutomaticRifleman': 'Soldier USMC Automatic Rifleman',
	'BP_Soldier_USMC_AutomaticRifleman2': 'Soldier USMC Automatic Rifleman2',
	'BP_Soldier_USMC_AutomaticRifleman_Woodland': 'Soldier USMC Automatic Rifleman Woodland',
	'BP_Soldier_USMC_Crewman': 'Soldier USMC Crewman',
	'BP_Soldier_USMC_Crewman_Woodland': 'Soldier USMC Crewman Woodland',
	'BP_Soldier_USMC_Engineer': 'Soldier USMC Engineer',
	'BP_Soldier_USMC_Engineer_Woodland': 'Soldier USMC Engineer Woodland',
	'BP_Soldier_USMC_Grenadier': 'Soldier USMC Grenadier',
	'BP_Soldier_USMC_Grenadier_Woodland': 'Soldier USMC Grenadier Woodland',
	'BP_Soldier_USMC_HAT': 'Soldier USMC HAT',
	'BP_Soldier_USMC_LAT_AT4': 'Soldier USMC LAT AT4',
	'BP_Soldier_USMC_LAT_AT4_Woodland': 'Soldier USMC LAT AT4 Woodland',
	'BP_Soldier_USMC_LAT_M72': 'Soldier USMC LAT M72',
	'BP_Soldier_USMC_MachineGunner': 'Soldier USMC Machine Gunner',
	'BP_Soldier_USMC_Medic': 'Soldier USMC Medic',
	'BP_Soldier_USMC_SquadLeader': 'Soldier USMC Squad Leader',
	'BP_Soldier_VDV2_AutomaticRifleman_2': 'Soldier VDV2 Automatic Rifleman 2',
	'BP_Soldier_VDV2_Engineer_Desert': 'Soldier VDV2 Engineer Desert',
	'BP_Soldier_VDV2_Grenadier': 'Soldier VDV2 Grenadier',
	'BP_Soldier_VDV2_Grenadier_Desert_RGF': 'Soldier VDV2 Grenadier Desert RGF',
	'BP_Soldier_VDV2_LAT_RPG22_Desert_RGF': 'Soldier VDV2 LAT RPG22 Desert RGF',
	'BP_Soldier_VDV2_LAT_RPG26_Desert': 'Soldier VDV2 LAT RPG26 Desert',
	'BP_Soldier_VDV2_Machinegunner': 'Soldier VDV2 Machinegunner',
	'BP_Soldier_VDV2_Marksman': 'Soldier VDV2 Marksman',
	'BP_Soldier_VDV2_Medic_2': 'Soldier VDV2 Medic 2',
	'BP_Soldier_VDV2_Rifleman2': 'Soldier VDV2 Rifleman2',
	'BP_Soldier_VDV_SL_Crewman_Desert': 'Soldier VDV Squad Leader Crewman Desert',
	'BP_Soldier_VDV_SL_Pilot': 'Soldier VDV Squad Leader Pilot',
	'BP_Soldier_VDV_SL_Pilot_Desert': 'Soldier VDV Squad Leader Pilot Desert',
	'BP_Soldier_VDV_Sniper': 'Soldier VDV Sniper',
	'BP_Soldier_VDV_Sniper_Desert': 'Soldier VDV Sniper Desert',
	'BP_Soldiers_CRF_Automatic_Rifleman_02': 'Soldiers CRF Automatic Rifleman 02',
	'BP_Soldiers_CRF_SL_05': 'Soldiers CRF Squad Leader 05',
	'BP_Soldiers_WPMC_Machinegunner_01': 'Soldiers WPMC Machinegunner 01',
	'BP_Soldiers_WPMC_Marskman_01': 'Soldiers WPMC Marskman 01',
	'BP_Soldiers_WPMC_Medic_01': 'Soldiers WPMC Medic 01',
	'BP_Soldiers_WPMC_Raider_02': 'Soldiers WPMC Raider 02',
	'BP_Soldiers_WPMC_Rifleman_02': 'Soldiers WPMC Rifleman 02',
	'BP_Soldiers_WPMC_Rifleman_03': 'Soldiers WPMC Rifleman 03',
	'BP_Soldiers_WPMC_Rifleman_08': 'Soldiers WPMC Rifleman 08',
	'BP_Soldiers_WPMC_SL_01': 'Soldiers WPMC Squad Leader 01',
	'BP_Soldiers_WPMC_SL_02': 'Soldiers WPMC Squad Leader 02',
	'BP_Soldiers_WPMC_SL_Crewman_01': 'Soldiers WPMC Squad Leader Crewman 01',
	'BP_Soldiers_WPMC_SL_Pilot_01': 'Soldiers WPMC Squad Leader Pilot 01',
	'BP_Soldiers_WPMC_Sapper_01': 'Soldiers WPMC Sapper 01',
	'BP_Sprut_Desert': 'Sprut Desert',
	'BP_StugnaP_Proj': 'Stugna P Projectile',
	'BP_T62': 'T62',
	'BP_T62_MIL': 'T62 Militia',
	'BP_T64BM2_Cage': 'T64BM2 Cage',
	'BP_T72A_IMF': 'T72A IMF',
	'BP_T84_Cupola_Weapon': 'T84 Cupola Weapon',
	'BP_T90A': 'T90A',
	'BP_T90A_Ammocook': 'T90A Ammo Cookoff',
	'BP_TKC_AR_MEE': 'TKC Automatic Rifleman MEE',
	'BP_TKC_Engineer_MEE': 'TKC Engineer MEE',
	'BP_TKC_Medic_MEE': 'TKC Medic MEE',
	'BP_TKC_SL_MEE': 'TKC Squad Leader MEE',
	'BP_TLF_Util_Truck_Desert': 'TLF Util Truck Desert',
	'BP_Technical_BMP1_PKT': 'Technical BMP1 PKT',
	'BP_Turret_ZPU1_Antiaircannon_Weapon': 'Turret ZPU1 Antiaircannon Weapon',
	'BP_Type63_Rocket_Proj2': 'Type63 Rocket Projectile',
	'BP_UH1Y': 'UH1Y',
	'BP_UKSF_Extra_1': 'UKSF Extra 1',
	'BP_UKSF_HAT': 'UKSF HAT',
	'BP_UKSF_Rifleman_DMR': 'UKSF Rifleman DMR',
	'BP_UKSF_Rifleman_Grenadier': 'UKSF Rifleman Grenadier',
	'BP_UKSF_Rifleman_LAT': 'UKSF Rifleman LAT',
	'BP_UKSF_SL': 'UKSF Squad Leader',
	'BP_USF_HAT_NLAW': 'USF HAT NLAW',
	'BP_USF_MG': 'USF MG',
	'BP_USF_Rifleman_545': 'USF Rifleman 545',
	'BP_USF_Rifleman_556': 'USF Rifleman 556',
	'BP_Ural375_BM21_MEI_Destroyed': 'Ural375 BM21 MEI Destroyed',
	'BP_Ural_4320_logi_GFI': 'Ural 4320 logi GFI',
	'BP_VAB_Destroy': 'VAB Destroyed',
	'BP_VPC_Destroy': 'VPC Destroyed',
	'BP_VP_BMP-2_30mm_HE_Green': 'VP BMP 2 30mm High Explosive Green',
	'BP_VW_BMD-2M_2A42_AP_Forest': 'Volkswagen BMD 2M 2A42 Armor Piercing Forest',
	'BP_VW_BMP-2_2A42_AP_RGF_Forest': 'Volkswagen BMP 2 2A42 Armor Piercing RGF Forest',
	'BP_VW_BMP-2__PKT_RGF_Forest': 'Volkswagen BMP 2 PKT RGF Forest',
	'BP_VW_Eitan_RWS_M2': 'Volkswagen Eitan RWS M2 .50 cal HMG',
	'BP_VW_VPC_M2_Parent': 'Volkswagen VPC M2 .50 cal HMG',
	'BP_V_BMD-2M_Forest': 'V BMD 2M Forest',
	'BP_V_CH-47_TRAN_USA': 'V CH 47 TRAN USA',
	'BP_V_MRH-90_CAS_ADF': 'V MRH 90 CAS ADF',
	'BP_V_Mi-26_Green': 'V Mi 26 Green',
	'BP_V_Mi-8_CAS_IAGF': 'V Mi 8 CAS IAGF',
	'BP_V_PUMA_Forest': 'V PUMA Forest',
	'BP_V_Typhoon_2A42_AP_Green': 'V Typhoon 2A42 Armor Piercing Green',
	'BP_WZ551A': 'WZ551A',
	'BP_Warrior_Rarden_HE': 'Warrior Rarden High Explosive',
	'BP_Z8G': 'Z8G',
	'BP_ZBD04A_2A70_HEFrag': 'ZBD04A 2A70 High Explosive Fragmentation',
	'BP_ZBD05_HJ73C': 'ZBD05 HJ73C',
	'BP_ZBD05_ZPT-99_HE': 'ZBD05 ZPT 99 High Explosive',
	'BP_ZBL08_HJ73C': 'ZBL08 HJ73C',
	'BP_ZBL08_ZPT-99_HEFrag': 'ZBL08 ZPT 99 High Explosive Fragmentation',
	'BP_ZPT-98_HE': 'ZPT 98 High Explosive',
	'BP_ZPT-98_HEAT': 'ZPT 98 HEAT',
	'BP_ZPT-98_HE_SPM': 'ZPT 98 High Explosive SPM',
	'BP_ZSD05_Logi': 'ZSD05 Logistics',
	'BP_ZSD05_QJZ-89': 'ZSD05 QJZ-89',
	'BP_ZSD89': 'ZSD89',
	'BP_ZSD89_QLZ-87': 'ZSD89 QLZ 87',
	'BP_ZSU-23-4_Weapon_MEIMF': 'ZSU 23 4 Weapon ME IMF',
	'BP_ZTD05': 'ZTD05',
	'BP_ZTD05_WoodLand': 'ZTD05 Wood Land',
	'BP_ZTD05_ZPL-98A_HEAT': 'ZTD05 ZPL 98A HEAT',
	'BP_ZTZ99_wCage': 'ZTZ99 w Cage',
	'BP_ZTZ99_wCage_Desert_PLA': 'ZTZ99 w Cage Desert PLA',
	'BP_ZTZ99_wCage_Woodland_PLA': 'ZTZ99 w Cage Woodland PLA',
	'BTR-MDM_Desert_Destroy': 'BTR MDM Desert Destroyed',
	'BTR-ZD_Destroy': 'BTR ZD Destroyed',
	'BTR4_Burned': 'BTR4 Burned',
	'BTR4_Destroy': 'BTR4 Destroyed',
	'BritUtilTruck_Obliterate': 'British Util Truck Obliterated',
	'CAF_Util_Burn_desert': 'CAF Util Burned desert',
	'CAF_Util_Obliterate_desert': 'CAF Util Obliterated desert',
	'CAF_Util_destroyed_desert': 'CAF Util Destroyed desert',
	'CAF_Util_destroyed_woodland': 'CAF Util Destroyed woodland',
	'CH146_Crash_Desert': 'CH146 Crash Desert',
	'CH146_Destroyed': 'CH146 Destroyed',
	'CPV_Destroyed': 'CPV Destroyed',
	'CSK_destroyed': 'CSK Destroyed',
	'CSK_destroyed_Naval': 'CSK Destroyed Naval',
	'CSK_obliterate': 'CSK Obliterated',
	'CTM131_Destroyed': 'CTM131 Destroyed',
	'CTM131_destroyed_Naval': 'CTM131 Destroyed Naval',
	'Cobra2_Destroyed_Desert': 'Cobra2 Destroyed Desert',
	'DirtBike_destroyed': 'Dirt Bike Destroyed',
	'FV432_Burn': 'FV432 Burned',
	'FV432_Obliterate': 'FV432 Obliterated',
	'FV432_Woodland_Burn': 'FV432 Woodland Burned',
	'FV432_Woodland_Obliterate': 'FV432 Woodland Obliterated',
	'FV432_Woodland_destroyed': 'FV432 Woodland Destroyed',
	'FV432_destroyed': 'FV432 Destroyed',
	'IFV25_M252_AP': 'IFV25 M252 Armor Piercing',
	'IFV25_M252_AP_Desert': 'IFV25 M252 Armor Piercing Desert',
	'IFV25_M252_HE': 'IFV25 M252 High Explosive',
	'LAV25_Burn': 'LAV25 Burned',
	'LAV25_Destroyed': 'LAV25 Destroyed',
	'LAV25_M252_HE': 'LAV25 M252 High Explosive',
	'LAV25_Woodland_AmmoCook': 'LAV25 Woodland Ammo Cookoff',
	'LAV25_Woodland_Burn': 'LAV25 Woodland Burned',
	'LAV25_Woodland_Destroyed': 'LAV25 Woodland Destroyed',
	'LAV_M252_HE': 'LAV M252 High Explosive',
	'LAV_M252_HE_Desert': 'LAV M252 High Explosive Desert',
	'LPPV_Woodland_Destroyed': 'LPPV Woodland Destroyed',
	'LUVW_destroyed_turret': 'LUVW Destroyed turret',
	'Loach_Crash': 'Loach Crash',
	'Loach_Crash_CAS': 'Loach Crash CAS',
	'Loach_Destroyed_CAS': 'Loach Destroyed CAS',
	'M1151_Light_destroyed_Woodland': 'M1151 Light Destroyed Woodland',
	'M1151_destroyed_Light_Woodland_Burn': 'M1151 Destroyed Light Woodland Burned',
	'M1a1_USMC_Destroyed': 'M1a1 USMC Destroyed',
	'M1a2_Burned_ADF': 'M1a2 Burned ADF',
	'M1a2_Knockedout_ADF': 'M1a2 Knocked Out ADF',
	'M60T_Destroy': 'M60T Destroyed',
	'MATV_USMC_destroyed_CROWS': 'MATV USMC Destroyed CROWS',
	'MATV_USMC_destroyed_CROWS_Woodland': 'MATV USMC Destroyed CROWS Woodland',
	'MI8_Crash': 'MI8 Crash',
	'MI8_Crash_AFU': 'MI8 Crash AFU',
	'MI8_Destroyed': 'MI8 Destroyed',
	'MI8_Destroyed_Grey': 'MI8 Destroyed Grey',
	'P4_destroyed_Forest': 'P4 Destroyed Forest',
	'PARS3_Sancak_Ammocook': 'PARS3 Sancak Ammo Cookoff',
	'PARS3_Sancak_Burn': 'PARS3 Sancak Burned',
	'PARS3_Sancak_Burn_Desert': 'PARS3 Sancak Burned Desert',
	'PARS3_Sancak_Destroyed': 'PARS3 Sancak Destroyed',
	'PMV_destroyed': 'PMV Destroyed',
	'PMV_destroyed_obliterate': 'PMV Destroyed Obliterated',
	'RHIB_Destroyed': 'RHIB Destroyed',
	'Raven_Crash_WPMC': 'Raven Crash WPMC',
	'SA330_Crash': 'SA330 Crash',
	'SA342_FRA_Woodland_Destroyed': 'SA342 FRA Woodland Destroyed',
	'SK_MEIMF_Rifleman': 'SK ME IMF Rifleman',
	'Scimitar_Destroy': 'Scimitar Destroyed',
	'Scimitar_Woodland_AmmoCook': 'Scimitar Woodland Ammo Cookoff',
	'Scimitar_Woodland_Destroy': 'Scimitar Woodland Destroyed',
	'T62_Ammocook': 'T62 Ammo Cookoff',
	'T62_Destroy': 'T62 Destroyed',
	'T64BM2_Ammocook': 'T64BM2 Ammo Cookoff',
	'T64BM2_Destroy': 'T64BM2 Destroyed',
	'T72_Destroy': 'T72 Destroyed',
	'TAPV_destroyed': 'TAPV Destroyed',
	'TAPV_obliterate': 'TAPV Obliterated',
	'Technical_2Seater_Obliterate': 'Technical 2Seater Obliterated',
	'Technical_4Seater_Camo_destroyed': 'Technical 4Seater Camo Destroyed',
	'Technical_4Seater_Obliterate': 'Technical 4Seater Obliterated',
	'Tigr_destroyed': 'Tigr Destroyed',
	'Tigr_destroyed_Desert': 'Tigr Destroyed Desert',
	'Tigr_destroyed_MIL': 'Tigr Destroyed Militia',
	'Tigr_obliterate': 'Tigr Obliterated',
	'Tigr_obliterate_MIL': 'Tigr Obliterated Militia',
	'US_Util_destroyed_CRF': 'US Util Destroyed CRF',
	'WPMC_Technical_4Seater_destroyed_Black': 'WPMC Technical 4Seater Destroyed Black',
	'WPMC_Util_destroyed_Black': 'WPMC Util Destroyed Black',
	'WZ551_Burned': 'WZ551 Burned',
	'Warrior_Destroy': 'Warrior Destroyed',
	'Z8G_Crash': 'Z8G Crash',
	'Z8G_Destroyed': 'Z8G Destroyed',
	'Z8J_Destroyed': 'Z8J Destroyed',
	'ZBD04A_Destroy': 'ZBD04A Destroyed',
	'ZBD05_Ammocook': 'ZBD05 Ammo Cookoff',
	'ZBD05_Burn': 'ZBD05 Burned',
	'ZBL08_Ammocook': 'ZBL08 Ammo Cookoff',
	'ZBL08_Ammocook_Desert': 'ZBL08 Ammo Cookoff Desert',
	'ZBL08_Burn': 'ZBL08 Burned',
	'ZBL08_Destroy': 'ZBL08 Destroyed',
	'ZSD-05_Burn_Woodland': 'ZSD-05 Burned Woodland',
	'ZSD89_Burn_Desert': 'ZSD89 Burned Desert',
	'ZSD89_Destroy': 'ZSD89 Destroyed',
	'ZSL-10_Burn': 'ZSL-10 Burned',
	'ZTD05_Ammocook': 'ZTD05 Ammo Cookoff',
	'ZTD05_Burn': 'ZTD05 Burned',
	'ZTZ99_Ammocook_wCage': 'ZTZ99 Ammo Cookoff w Cage',
	'ZTZ99_Burn_wCage': 'ZTZ99 Burned w Cage',
	'ZTZ99_Destroy': 'ZTZ99 Destroyed',
	'ZTZ99_Destroy_Desert_wCage': 'ZTZ99 Destroyed Desert w Cage',
	'ZTZ99_Destroy_wCage': 'ZTZ99 Destroyed w Cage',
	'brdm2_Burn_AFU': 'Brdm2 Burned AFU',
	'brdm2_Obliterate_AFU': 'Brdm2 Obliterated AFU',
	'brdm2_wreck_MEIMF': 'Brdm2 Wreck ME IMF',
	'brdm2_wreck_Rus': 'Brdm2 Wreck Rus',
	'btr_80_Burned': 'Btr 80 Burned',
	'btr_80_Destroy': 'Btr 80 Destroyed',
	'btr_82_Destroy': 'Btr 82 Destroyed',
	'kamaz_5350_Desert_Burn': 'Kamaz 5350 Desert Burned',
	'kamaz_5350_Obliterate': 'Kamaz 5350 Obliterated',
	'kamaz_5350_desert_Obliterate': 'Kamaz 5350 desert Obliterated',
	'kraz_6322_burn': 'Kraz 6322 Burned',
	'kraz_6322_obliterate': 'Kraz 6322 Obliterated',
	'lav6_AmmoCook_Desert': 'Lav6 Ammo Cookoff Desert',
	'lav6_Burn': 'Lav6 Burned',
	'stryker_Obliterate': 'Stryker Obliterated',
	'ural375_militia_Burn': 'Ural375 militia Burned',
};

export const knownWeapons = Object.fromEntries(Object.entries(weapons).map(([key, value]) => ([key.toLowerCase(), value])));
